<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: /mnt/c/Users/abell/Documents/GitHub/NRE-Math/src/Math/NRE_Math.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li><a href="globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php">Math</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Math.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_math_2_n_r_e___math_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;cmath&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;type_traits&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_math.php">Math</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;    </div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class </span>...&gt;</div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">   31</a></span>&#160;            <span class="keyword">struct </span><a class="code" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">ArithmeticChecker</a> : std::true_type {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            };</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class </span>T1, <span class="keyword">class </span>... Tn&gt;</div><div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker_3_01_t1_00_01_tn_8_8_8_01_4.php">   38</a></span>&#160;            <span class="keyword">struct </span><a class="code" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">ArithmeticChecker</a>&lt;T1, Tn...&gt; : std::conjunction&lt;std::conjunction&lt;ArithmeticChecker&lt;Tn...&gt;&gt;, std::is_arithmetic&lt;T1&gt;&gt; {</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;            };</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T1&gt;</div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker_3_01_t1_01_4.php">   45</a></span>&#160;            <span class="keyword">struct </span><a class="code" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">ArithmeticChecker</a>&lt;T1&gt; : std::is_arithmetic&lt;T1&gt; {</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;            };</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;            </div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class </span>... Tn&gt;</div><div class="line"><a name="l00049"></a><span class="lineno"><a class="line" href="_math_2_n_r_e___math_8hpp.php#afe8b0dbf09256f60552e15fd31a3e650">   49</a></span>&#160;            constexpr <span class="keywordtype">bool</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#afe8b0dbf09256f60552e15fd31a3e650">ArithmeticCheckerV</a> = <a class="code" href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">ArithmeticChecker</a>&lt;Tn...&gt;::value; </div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class </span>... Tn&gt;</div><div class="line"><a name="l00053"></a><span class="lineno"><a class="line" href="_math_2_n_r_e___math_8hpp.php#a1202e62391de93b7179399a05563c746">   53</a></span>&#160;            <span class="keyword">using</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#a1202e62391de93b7179399a05563c746">UseIfArithmetic</a> = std::enable_if_t&lt;ArithmeticCheckerV&lt;Tn...&gt;&gt;;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;            <span class="keyword">static</span> constexpr <span class="keywordtype">long</span> <span class="keywordtype">double</span> EPSILON = 0.000001;                            </div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;            <span class="keyword">static</span> constexpr <span class="keywordtype">long</span> <span class="keywordtype">double</span> PI = 3.141592653589793238462643383279502884L;  </div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> K, <span class="keyword">typename</span> std::enable_if_t&lt; std::is_<span class="keywordtype">float</span>ing_po<span class="keywordtype">int</span>&lt;std::common_type_t&lt;T, K&gt;&gt;::value, <span class="keywordtype">int</span>&gt; = 0&gt;</div><div class="line"><a name="l00065"></a><span class="lineno"><a class="line" href="_math_2_n_r_e___math_8hpp.php#a296fb149791d6f1512ecb640697f7a9d">   65</a></span>&#160;            constexpr <span class="keywordtype">bool</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#a296fb149791d6f1512ecb640697f7a9d">equal</a>(T a, K b) {</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                <span class="keywordflow">return</span> std::abs(static_cast &lt;std::common_type_t&lt;T, K&gt;&gt; (a) - static_cast &lt;std::common_type_t&lt;T, K&gt;&gt; (b)) &lt; EPSILON;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;            }</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;    </div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> K, <span class="keyword">typename</span> std::enable_if_t&lt;!std::is_<span class="keywordtype">float</span>ing_po<span class="keywordtype">int</span>&lt;std::common_type_t&lt;T, K&gt;&gt;::value, <span class="keywordtype">int</span>&gt; = 0&gt;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;            constexpr <span class="keywordtype">bool</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#a296fb149791d6f1512ecb640697f7a9d">equal</a>(T a, K b) {</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                <span class="keywordflow">return</span> static_cast &lt;std::common_type_t&lt;T, K&gt;&gt; (a) == static_cast &lt;std::common_type_t&lt;T, K&gt;&gt; (b);</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;            }</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> K&gt;</div><div class="line"><a name="l00086"></a><span class="lineno"><a class="line" href="_math_2_n_r_e___math_8hpp.php#a14c9467bb40a8410763c5783a056839e">   86</a></span>&#160;            constexpr <span class="keywordtype">bool</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#a14c9467bb40a8410763c5783a056839e">almostEqual</a>(T a, K b) {</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                <span class="keywordflow">return</span> <a class="code" href="_math_2_n_r_e___math_8hpp.php#a296fb149791d6f1512ecb640697f7a9d">equal</a>(a, b);</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;            }</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">typename</span> = UseIfArithmetic&lt;T&gt;&gt;</div><div class="line"><a name="l00097"></a><span class="lineno"><a class="line" href="_math_2_n_r_e___math_8hpp.php#a59f1ae1feff8a4d64bba70efedfffd53">   97</a></span>&#160;            constexpr T <a class="code" href="_math_2_n_r_e___math_8hpp.php#a59f1ae1feff8a4d64bba70efedfffd53">lerp</a>(T <span class="keyword">const</span>&amp; a, T <span class="keyword">const</span>&amp; b, <span class="keywordtype">float</span> <span class="keyword">const</span>&amp; f) {</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;                <span class="keywordflow">return</span> a * (1.0f - f) + b * f;</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;            }</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        }</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    }</div><div class="ttc" id="_math_2_n_r_e___math_8hpp_php_a1202e62391de93b7179399a05563c746"><div class="ttname"><a href="_math_2_n_r_e___math_8hpp.php#a1202e62391de93b7179399a05563c746">NRE::Math::UseIfArithmetic</a></div><div class="ttdeci">std::enable_if_t&lt; ArithmeticCheckerV&lt; Tn... &gt;&gt; UseIfArithmetic</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:53</div></div>
<div class="ttc" id="_math_2_n_r_e___math_8hpp_php_a296fb149791d6f1512ecb640697f7a9d"><div class="ttname"><a href="_math_2_n_r_e___math_8hpp.php#a296fb149791d6f1512ecb640697f7a9d">NRE::Math::equal</a></div><div class="ttdeci">constexpr bool equal(T a, K b)</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:65</div></div>
<div class="ttc" id="namespace_math_php"><div class="ttname"><a href="namespace_math.php">Math</a></div><div class="ttdoc">Math&amp;#39;s API. </div></div>
<div class="ttc" id="_math_2_n_r_e___math_8hpp_php_afe8b0dbf09256f60552e15fd31a3e650"><div class="ttname"><a href="_math_2_n_r_e___math_8hpp.php#afe8b0dbf09256f60552e15fd31a3e650">NRE::Math::ArithmeticCheckerV</a></div><div class="ttdeci">constexpr bool ArithmeticCheckerV</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:49</div></div>
<div class="ttc" id="struct_n_r_e_1_1_math_1_1_arithmetic_checker_php"><div class="ttname"><a href="struct_n_r_e_1_1_math_1_1_arithmetic_checker.php">NRE::Math::ArithmeticChecker</a></div><div class="ttdoc">Template structure allowing compile-time check on template parameters if they are arithmetic or not...</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:31</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="_math_2_n_r_e___math_8hpp_php_a59f1ae1feff8a4d64bba70efedfffd53"><div class="ttname"><a href="_math_2_n_r_e___math_8hpp.php#a59f1ae1feff8a4d64bba70efedfffd53">NRE::Math::lerp</a></div><div class="ttdeci">constexpr T lerp(T const &amp;a, T const &amp;b, float const &amp;f)</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:97</div></div>
<div class="ttc" id="_math_2_n_r_e___math_8hpp_php_a14c9467bb40a8410763c5783a056839e"><div class="ttname"><a href="_math_2_n_r_e___math_8hpp.php#a14c9467bb40a8410763c5783a056839e">NRE::Math::almostEqual</a></div><div class="ttdeci">constexpr bool almostEqual(T a, K b)</div><div class="ttdef"><b>Definition:</b> NRE_Math.hpp:86</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
