<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Curve/Bezier/4D/NRE_BezierCurve4D.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php">Math</a></li><li class="navelem"><a class="el" href="dir_732818e93b72bb0dfd477c5bec1e8d99.php">Curve</a></li><li class="navelem"><a class="el" href="dir_70006416f45ccac6628fade1908531f2.php">Bezier</a></li><li class="navelem"><a class="el" href="dir_4cb2f31512a0324f40e2ec79e38adf51.php">4D</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_BezierCurve4D.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___bezier_curve4_d_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;Utility/Vector/NRE_Vector.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &lt;Utility/Interfaces/Stringable/NRE_Stringable.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">     #include &quot;../../../Vector/4D/NRE_Vector4D.hpp&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_math.php">Math</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">   32</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a> : <span class="keyword">public</span> Utility::Stringable&lt;BezierCurve4D&gt; {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    Utility::Vector&lt;Point4D&lt;float&gt;&gt; controls;   </div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac2c5db9079a354e315a9791e605a4c0f">BezierCurve4D</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a2d7167d43835fa7e59aa1686fc60491d">   46</a></span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a2d7167d43835fa7e59aa1686fc60491d">BezierCurve4D</a>(std::initializer_list&lt;<a class="code" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D&lt;float&gt;</a>&gt; points) : controls(points) {</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                        }</div><div class="line"><a name="l00052"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a07cfaa85fe7f01978df90cc5d8da7745">   52</a></span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a07cfaa85fe7f01978df90cc5d8da7745">BezierCurve4D</a>(Utility::Vector&lt;<a class="code" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D&lt;float&gt;</a>&gt; &amp;&amp; c) : controls(c) {</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                        }</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac2c5db9079a354e315a9791e605a4c0f">BezierCurve4D</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a> <span class="keyword">const</span>&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac2c5db9079a354e315a9791e605a4c0f">BezierCurve4D</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a> &amp;&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a55cf4d9eff91a6895acb187e2414bfa8">~BezierCurve4D</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00081"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ab3f98702f37d9a46a9b9c1bc47dfcf06">   81</a></span>&#160;<span class="comment"></span>                        <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D&lt;float&gt;</a> <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ab3f98702f37d9a46a9b9c1bc47dfcf06">getPoint</a>(std::size_t index)<span class="keyword"> const </span>{</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                            <span class="keywordflow">return</span> controls[index];</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                        }</div><div class="line"><a name="l00088"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac60fa3c1501c7f4b584f0d494f6d1281">   88</a></span>&#160;                        <span class="keyword">inline</span> std::size_t <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac60fa3c1501c7f4b584f0d494f6d1281">getSize</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                            <span class="keywordflow">return</span> controls.getSize();</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                        }</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                    <span class="comment">//## Access Operator ##//</span></div><div class="line"><a name="l00099"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a12f9875f93a1f9ce6aea62cad3734d2b">   99</a></span>&#160;<span class="comment"></span>                        <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D&lt;float&gt;</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a12f9875f93a1f9ce6aea62cad3734d2b">operator []</a>(std::size_t index) {</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                            <span class="keywordflow">return</span> controls[index];</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        }</div><div class="line"><a name="l00108"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac94b8c3dbbf510f85580bb2761c402e7">  108</a></span>&#160;                         <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D&lt;float&gt;</a> <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac94b8c3dbbf510f85580bb2761c402e7">operator []</a>(std::size_t index)<span class="keyword"> const</span>{</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                             <span class="keywordflow">return</span> controls[index];</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;                         }</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a> <span class="keyword">const</span>&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a> &amp;&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a6de39ef8fa0b8a96955f46f10e963afd">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;            };</div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;        }</div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;    }</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;<span class="preprocessor">    #include &quot;NRE_BezierCurve4D.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_ac60fa3c1501c7f4b584f0d494f6d1281"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac60fa3c1501c7f4b584f0d494f6d1281">NRE::Math::BezierCurve4D::getSize</a></div><div class="ttdeci">std::size_t getSize() const</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:88</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a5d40d8cd0a22a3dec6153b16fcff37b2"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">NRE::Math::BezierCurve4D::operator=</a></div><div class="ttdeci">BezierCurve4D &amp; operator=(BezierCurve4D const &amp;c)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a12f9875f93a1f9ce6aea62cad3734d2b"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a12f9875f93a1f9ce6aea62cad3734d2b">NRE::Math::BezierCurve4D::operator []</a></div><div class="ttdeci">Point4D&lt; float &gt; &amp; operator [](std::size_t index)</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:99</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_ac2c5db9079a354e315a9791e605a4c0f"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac2c5db9079a354e315a9791e605a4c0f">NRE::Math::BezierCurve4D::BezierCurve4D</a></div><div class="ttdeci">BezierCurve4D()=default</div></div>
<div class="ttc" id="namespace_math_php"><div class="ttname"><a href="namespace_math.php">Math</a></div><div class="ttdoc">Math's API.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_ab3f98702f37d9a46a9b9c1bc47dfcf06"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ab3f98702f37d9a46a9b9c1bc47dfcf06">NRE::Math::BezierCurve4D::getPoint</a></div><div class="ttdeci">Point4D&lt; float &gt; const  &amp; getPoint(std::size_t index) const</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:81</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a07cfaa85fe7f01978df90cc5d8da7745"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a07cfaa85fe7f01978df90cc5d8da7745">NRE::Math::BezierCurve4D::BezierCurve4D</a></div><div class="ttdeci">BezierCurve4D(Utility::Vector&lt; Point4D&lt; float &gt;&gt; &amp;&amp;c)</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:52</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine's global namespace.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_vector4_d_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_vector4_d.php">NRE::Math::Vector4D</a></div><div class="ttdoc">A cartesian 4D vector, 3D homogeneous.</div><div class="ttdef"><b>Definition:</b> NRE_Matrix4x4.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_ac94b8c3dbbf510f85580bb2761c402e7"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac94b8c3dbbf510f85580bb2761c402e7">NRE::Math::BezierCurve4D::operator []</a></div><div class="ttdeci">Point4D&lt; float &gt; const  &amp; operator [](std::size_t index) const</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:108</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a55cf4d9eff91a6895acb187e2414bfa8"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a55cf4d9eff91a6895acb187e2414bfa8">NRE::Math::BezierCurve4D::~BezierCurve4D</a></div><div class="ttdeci">~BezierCurve4D()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a6de39ef8fa0b8a96955f46f10e963afd"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a6de39ef8fa0b8a96955f46f10e963afd">NRE::Math::BezierCurve4D::toString</a></div><div class="ttdeci">Utility::String toString() const</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php_a2d7167d43835fa7e59aa1686fc60491d"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a2d7167d43835fa7e59aa1686fc60491d">NRE::Math::BezierCurve4D::BezierCurve4D</a></div><div class="ttdeci">BezierCurve4D(std::initializer_list&lt; Point4D&lt; float &gt;&gt; points)</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:46</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_bezier_curve4_d_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></div><div class="ttdoc">Represent a 3D homogeneous Bezier curves with a set of control points.</div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve4D.hpp:32</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
