<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: /mnt/c/Users/abell/Documents/GitHub/NRE-Math/src/Math/Quaternion/NRE_Quaternion.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li><a href="globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php">Math</a></li><li class="navelem"><a class="el" href="dir_3bdf3edcab80ec8aaf365e04700bf3c7.php">Quaternion</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Quaternion.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___quaternion_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &lt;iostream&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">     #include &quot;../NRE_Math.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">     #include &quot;../NRE_Unit.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_math.php">Math</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keyword">template</span>&lt;<span class="keyword">class</span>&gt; <span class="keyword">class </span>Vector3D;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;            <span class="keyword">template</span>&lt;<span class="keyword">class</span>&gt; <span class="keyword">class </span>Vector4D;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;            <span class="keyword">class </span>Quaternion {</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keyword">private</span> :   <span class="comment">//Fields</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    Vector4D&lt;T&gt; quat;   </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                <span class="keyword">public</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>();</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(T x, T y, T z, T w);</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(T x, T y, T z, Angle w);</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(Vector3D&lt;T&gt; <span class="keyword">const</span>&amp; ax, T an);</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(Vector3D&lt;T&gt; <span class="keyword">const</span>&amp; ax, Angle an);</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> <span class="keyword">const</span>&amp; q) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> &amp;&amp; q) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a26b086d5b95d53024ad36e8e9141ea29">~Quaternion</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;<span class="comment"></span>                        T <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa0717eaee838e8a29dc6171a7adf2b73">getX</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;                        T <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2e025252dbd1aae5b9e610e856c745c2">getY</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                        T <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#ad19616cc2549941bac2569549d379131">getZ</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                        T <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac1e7605f337578de78e84c7087480f4a">getW</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                        Vector3D&lt;T&gt; <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a69cdacf9fabe116ef083ab918ac2865a">getAxis</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        Vector4D&lt;T&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a51183223d4b9c7955bbe03d0147b48ff">getQuaternion</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                    <span class="comment">//## Setter ##//</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a94d23755f70656859a0fa8512f90079c">setX</a>(T x);</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a4cf7a35dcd77f6ceb53af34b344aa826">setY</a>(T y);</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a4037191f26b8fe6afc3245b06caebe6b">setZ</a>(T z);</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#aaa64ad7e7e8402b450ec601f87e40665">setW</a>(T w);</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a23d8d5c15694d3df5560295434c9fa96">setAngleAxis</a>(Vector3D&lt;T&gt; <span class="keyword">const</span>&amp; axis, Angle w);</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">setIdentity</a>();</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;                    <span class="comment">//## Members ##//</span></div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;<span class="comment"></span>                        <span class="keywordtype">float</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a533b835d9116d56319c30113c6e57d3d">norm</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                        <span class="keywordtype">float</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#aedae5a73dcb72764073cf05d6d70e764">normSquared</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9361a0a54041ad7cf5d0bb706819b909">normalize</a>();</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;                        <span class="keyword">const</span> T* <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#af7e730e858812649b38fc1d3d68155a1">value</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a302245476a19a35d788e0959ce700028">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> <span class="keyword">const</span>&amp; q) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a302245476a19a35d788e0959ce700028">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> &amp;&amp; q) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;                    <span class="comment">//## Shortcut Operator ##//</span></div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a07bca41dad96c32b91199458f35ff904">operator*=</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> <span class="keyword">const</span>&amp; q);</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;                    <span class="comment">//## Arithmetic Operator ##//</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a3cc218b9d5c28670b311bbb319944003">operator*</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">Quaternion</a> <span class="keyword">const</span>&amp; q) <span class="keyword">const</span>;</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;</div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_math_1_1_quaternion.php#a6b212d1f08fc9a5935bd323b22b9c531">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;            };</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;</div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;            std::ostream&amp; operator &lt;&lt;(std::ostream&amp; stream, Quaternion&lt;T&gt; <span class="keyword">const</span>&amp; o);</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;        }</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    }</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;<span class="preprocessor">    #include &quot;NRE_Quaternion.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_ad19616cc2549941bac2569549d379131"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#ad19616cc2549941bac2569549d379131">NRE::Math::Quaternion::getZ</a></div><div class="ttdeci">T getZ() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a302245476a19a35d788e0959ce700028"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a302245476a19a35d788e0959ce700028">NRE::Math::Quaternion::operator=</a></div><div class="ttdeci">Quaternion &amp; operator=(Quaternion const &amp;q)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a9361a0a54041ad7cf5d0bb706819b909"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a9361a0a54041ad7cf5d0bb706819b909">NRE::Math::Quaternion::normalize</a></div><div class="ttdeci">void normalize()</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_aedae5a73dcb72764073cf05d6d70e764"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#aedae5a73dcb72764073cf05d6d70e764">NRE::Math::Quaternion::normSquared</a></div><div class="ttdeci">float normSquared() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a4037191f26b8fe6afc3245b06caebe6b"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a4037191f26b8fe6afc3245b06caebe6b">NRE::Math::Quaternion::setZ</a></div><div class="ttdeci">void setZ(T z)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a2e025252dbd1aae5b9e610e856c745c2"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a2e025252dbd1aae5b9e610e856c745c2">NRE::Math::Quaternion::getY</a></div><div class="ttdeci">T getY() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a69cdacf9fabe116ef083ab918ac2865a"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a69cdacf9fabe116ef083ab918ac2865a">NRE::Math::Quaternion::getAxis</a></div><div class="ttdeci">Vector3D&lt; T &gt; getAxis() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a51183223d4b9c7955bbe03d0147b48ff"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a51183223d4b9c7955bbe03d0147b48ff">NRE::Math::Quaternion::getQuaternion</a></div><div class="ttdeci">Vector4D&lt; T &gt; const &amp; getQuaternion() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_ac1e7605f337578de78e84c7087480f4a"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#ac1e7605f337578de78e84c7087480f4a">NRE::Math::Quaternion::getW</a></div><div class="ttdeci">T getW() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a07bca41dad96c32b91199458f35ff904"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a07bca41dad96c32b91199458f35ff904">NRE::Math::Quaternion::operator*=</a></div><div class="ttdeci">Quaternion &amp; operator*=(Quaternion const &amp;q)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a26b086d5b95d53024ad36e8e9141ea29"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a26b086d5b95d53024ad36e8e9141ea29">NRE::Math::Quaternion::~Quaternion</a></div><div class="ttdeci">~Quaternion()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a94d23755f70656859a0fa8512f90079c"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a94d23755f70656859a0fa8512f90079c">NRE::Math::Quaternion::setX</a></div><div class="ttdeci">void setX(T x)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a4cf7a35dcd77f6ceb53af34b344aa826"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a4cf7a35dcd77f6ceb53af34b344aa826">NRE::Math::Quaternion::setY</a></div><div class="ttdeci">void setY(T y)</div></div>
<div class="ttc" id="namespace_math_php"><div class="ttname"><a href="namespace_math.php">Math</a></div><div class="ttdoc">Math&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_af7e730e858812649b38fc1d3d68155a1"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#af7e730e858812649b38fc1d3d68155a1">NRE::Math::Quaternion::value</a></div><div class="ttdeci">const T * value() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_abcd15e9b7e239d606d0d5f1591f4d1fa"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#abcd15e9b7e239d606d0d5f1591f4d1fa">NRE::Math::Quaternion::Quaternion</a></div><div class="ttdeci">Quaternion()</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a6b212d1f08fc9a5935bd323b22b9c531"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a6b212d1f08fc9a5935bd323b22b9c531">NRE::Math::Quaternion::toString</a></div><div class="ttdeci">Utility::String toString() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_aaa64ad7e7e8402b450ec601f87e40665"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#aaa64ad7e7e8402b450ec601f87e40665">NRE::Math::Quaternion::setW</a></div><div class="ttdeci">void setW(T w)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a06ead9af6d624c1572b219a5a1825ce7"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">NRE::Math::Quaternion::setIdentity</a></div><div class="ttdeci">void setIdentity()</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_BezierCurve3D.cpp:14</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a3cc218b9d5c28670b311bbb319944003"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a3cc218b9d5c28670b311bbb319944003">NRE::Math::Quaternion::operator*</a></div><div class="ttdeci">Quaternion operator*(Quaternion const &amp;q) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a23d8d5c15694d3df5560295434c9fa96"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a23d8d5c15694d3df5560295434c9fa96">NRE::Math::Quaternion::setAngleAxis</a></div><div class="ttdeci">void setAngleAxis(Vector3D&lt; T &gt; const &amp;axis, Angle w)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_a533b835d9116d56319c30113c6e57d3d"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#a533b835d9116d56319c30113c6e57d3d">NRE::Math::Quaternion::norm</a></div><div class="ttdeci">float norm() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_quaternion_php_aa0717eaee838e8a29dc6171a7adf2b73"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_quaternion.php#aa0717eaee838e8a29dc6171a7adf2b73">NRE::Math::Quaternion::getX</a></div><div class="ttdeci">T getX() const </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
