<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Frustum/NRE_Frustum.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php">Math</a></li><li class="navelem"><a class="el" href="dir_04356fb591a35ec7606e545595262676.php">Frustum</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Frustum.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___frustum_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;Utility/Array/NRE_Array.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;Utility/Interfaces/Stringable/NRE_Stringable.hpp&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../NRE_Unit.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;../Plane/NRE_Plane.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &quot;../Vector/2D/NRE_Vector2D.hpp&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">    #include &quot;../Vector/3D/NRE_Vector3D.hpp&quot;</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">    #include &quot;../Matrix/4D/NRE_Matrix4x4.hpp&quot;</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_math.php">Math</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_math_1_1_frustum.php">   36</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> : <span class="keyword">public</span> Utility::Stringable&lt;Frustum&gt; {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    Utility::Array&lt;Plane&lt;float&gt;, 6&gt; planes; </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <a class="code" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D&lt;float&gt;</a> near;                   </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    <a class="code" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D&lt;float&gt;</a> far;                    </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <a class="code" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D&lt;float&gt;</a> dist;                   </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    <span class="keywordtype">float</span> ratio;                            </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    Angle fov;                              </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">Frustum</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">Frustum</a>(Angle fieldOfView, <span class="keywordtype">float</span> r, <a class="code" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D&lt;float&gt;</a> <span class="keyword">const</span>&amp; d);</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">Frustum</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> <span class="keyword">const</span>&amp; f) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">Frustum</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp; f) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a7e32828fa7c6145022ee29d986d75120">~Frustum</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    </div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_plane.php">Plane&lt;float&gt;</a> <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a70f0b8991bceffca3152731a42577296">getPlane</a>(std::size_t index) <span class="keyword">const</span>;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                    <span class="comment">//## Setter ##//</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a2f895c6408c8ffce5408d827dc98db81">setFov</a>(Angle fieldOfView);</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a4d5e50e09cd83a78e23be42de12c4ba5">computePlane</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; eye, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; forward, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; left, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; up);</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a74f1ee8b02acd171054e284c0f6e5812">computeProjectionMatrix</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">Matrix4x4&lt;float&gt;</a>&amp; m);</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#ab85a19a9bb6c7818e1708f3db30bf7ef">resize</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D&lt;std::size_t&gt;</a> <span class="keyword">const</span>&amp; size, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; eye, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; forward, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; left, <a class="code" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D&lt;float&gt;</a> <span class="keyword">const</span>&amp; up);</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#af7d9047612f776bbc49811f944cfddc7">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> <span class="keyword">const</span>&amp; f) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#af7d9047612f776bbc49811f944cfddc7">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp; f) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_math_1_1_frustum.php#a661c0844cf4014edabc7bbaed72862c9">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                <span class="keyword">private</span>:</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                    <span class="keywordtype">void</span> computeNearAndFar();</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;            };</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        }</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    }</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;<span class="preprocessor">    #include &quot;NRE_Frustum.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_math_1_1_vector2_d_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_vector2_d.php">NRE::Math::Vector2D&lt; float &gt;</a></div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a4d5e50e09cd83a78e23be42de12c4ba5"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a4d5e50e09cd83a78e23be42de12c4ba5">NRE::Math::Frustum::computePlane</a></div><div class="ttdeci">void computePlane(Point3D&lt; float &gt; const &amp;eye, Vector3D&lt; float &gt; const &amp;forward, Vector3D&lt; float &gt; const &amp;left, Vector3D&lt; float &gt; const &amp;up)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_ab85a19a9bb6c7818e1708f3db30bf7ef"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#ab85a19a9bb6c7818e1708f3db30bf7ef">NRE::Math::Frustum::resize</a></div><div class="ttdeci">void resize(Vector2D&lt; std::size_t &gt; const &amp;size, Point3D&lt; float &gt; const &amp;eye, Vector3D&lt; float &gt; const &amp;forward, Vector3D&lt; float &gt; const &amp;left, Vector3D&lt; float &gt; const &amp;up)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a70f0b8991bceffca3152731a42577296"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a70f0b8991bceffca3152731a42577296">NRE::Math::Frustum::getPlane</a></div><div class="ttdeci">Plane&lt; float &gt; const  &amp; getPlane(std::size_t index) const</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_matrix4x4_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4</a></div><div class="ttdoc">4x4 generic matrix</div><div class="ttdef"><b>Definition:</b> NRE_Matrix3x3.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a661c0844cf4014edabc7bbaed72862c9"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a661c0844cf4014edabc7bbaed72862c9">NRE::Math::Frustum::toString</a></div><div class="ttdeci">Utility::String toString() const</div></div>
<div class="ttc" id="namespace_math_php"><div class="ttname"><a href="namespace_math.php">Math</a></div><div class="ttdoc">Math's API.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a8b8191a8bfe6f2502871132501ea7338"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">NRE::Math::Frustum::Frustum</a></div><div class="ttdeci">Frustum()=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_af7d9047612f776bbc49811f944cfddc7"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#af7d9047612f776bbc49811f944cfddc7">NRE::Math::Frustum::operator=</a></div><div class="ttdeci">Frustum &amp; operator=(Frustum const &amp;f)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_vector3_d_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_vector3_d.php">NRE::Math::Vector3D</a></div><div class="ttdoc">A cartesian 3D vector, 2D homogeneous.</div><div class="ttdef"><b>Definition:</b> NRE_Matrix3x3.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_plane_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane</a></div><div class="ttdoc">A cartesian plane with a point and a vector.</div><div class="ttdef"><b>Definition:</b> NRE_Matrix4x4.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a2f895c6408c8ffce5408d827dc98db81"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a2f895c6408c8ffce5408d827dc98db81">NRE::Math::Frustum::setFov</a></div><div class="ttdeci">void setFov(Angle fieldOfView)</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine's global namespace.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a74f1ee8b02acd171054e284c0f6e5812"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a74f1ee8b02acd171054e284c0f6e5812">NRE::Math::Frustum::computeProjectionMatrix</a></div><div class="ttdeci">void computeProjectionMatrix(Matrix4x4&lt; float &gt; &amp;m)</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php_a7e32828fa7c6145022ee29d986d75120"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php#a7e32828fa7c6145022ee29d986d75120">NRE::Math::Frustum::~Frustum</a></div><div class="ttdeci">~Frustum()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_frustum_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_frustum.php">NRE::Math::Frustum</a></div><div class="ttdoc">A view frustum used with camera.</div><div class="ttdef"><b>Definition:</b> NRE_Frustum.hpp:36</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
