<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Segment/4D/NRE_Segment4D.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php">Math</a></li><li class="navelem"><a class="el" href="dir_3f75207e03159bed1664f9452b71f96b.php">Segment</a></li><li class="navelem"><a class="el" href="dir_cd2754b3e59abc673ffa513596c2d487.php">4D</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Segment4D.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___segment4_d_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &quot;../../Vector/4D/NRE_Vector4D.hpp&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &lt;Utility/Interfaces/Stringable/NRE_Stringable.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_math.php">Math</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;            <span class="keyword">class </span>Segment4D : <span class="keyword">public</span> Utility::Stringable&lt;Segment4D&lt;T&gt;&gt; {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                    Point4D&lt;T&gt; start;   </div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    Point4D&lt;T&gt; end;     </div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> K, <span class="keyword">class</span> L&gt;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>(Point4D&lt;K&gt; <span class="keyword">const</span>&amp; s, Point4D&lt;L&gt; <span class="keyword">const</span>&amp; e);</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> K, <span class="keyword">class</span> L&gt;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>(Point3D&lt;K&gt; <span class="keyword">const</span>&amp; s, Point3D&lt;L&gt; <span class="keyword">const</span>&amp; e);</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> K, <span class="keyword">class</span> L, <span class="keyword">class</span> N, <span class="keyword">class</span> M, <span class="keyword">class</span> O, <span class="keyword">class</span> P&gt;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>(K sX, L sY, N sZ, M eX, O eY, P eZ);</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a4b34216691323f07b1b833730605992f">~Segment4D</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;<span class="comment"></span>                        Point4D&lt;T&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ad5e7e797237e5eb4d4d9bb5e06c9f824">getStart</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                        Point4D&lt;T&gt; <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a7b1079202714af2f32b22daf3dd24923">getEnd</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                        Vector4D&lt;T&gt; <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aaa9d9c85b5c518b06d6ba58b1eef038a">getVector</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                        <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a>&amp; <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">operator =</a>(<a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                    <span class="comment">//## Comparison Operator ##//</span></div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> K&gt;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a720d442b5503d5640142f78082c6b002">operator ==</a>(Segment4D&lt;K&gt; <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> K&gt;</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a3cc16c6b435ad5bdeae49572e17b7509">operator !=</a>(Segment4D&lt;K&gt; <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aef6aa7bce89e68ebdec107d72cbd82cd">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;            };</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;        }</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;    }</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespacestd.php">std</a> {</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> K&gt;</div><div class="line"><a name="l00148"></a><span class="lineno"><a class="line" href="structstd_1_1common__type_3_01_n_r_e_1_1_math_1_1_segment4_d_3_01_t_01_4_00_01_n_r_e_1_1_math_1_1_segment4_d_3_01_k_01_4_01_4.php">  148</a></span>&#160;        <span class="keyword">struct </span>common_type&lt;<a class="code" href="namespace_n_r_e.php">NRE</a>::Math::Segment4D&lt;T&gt;, <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt;K&gt;&gt; {</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;            <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php">type</a> = <a class="code" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D&lt;common_type_t &lt; T, K&gt;</a>&gt;;</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;        };</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;    }</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;<span class="preprocessor">    #include &quot;NRE_Segment4D.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a></div><div class="ttdoc">A 4D homogeneous segment.</div><div class="ttdef"><b>Definition:</b> NRE_Matrix4x4.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a720d442b5503d5640142f78082c6b002"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a720d442b5503d5640142f78082c6b002">NRE::Math::Segment4D::operator==</a></div><div class="ttdeci">bool operator==(Segment4D&lt; K &gt; const &amp;s) const</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a4b34216691323f07b1b833730605992f"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a4b34216691323f07b1b833730605992f">NRE::Math::Segment4D::~Segment4D</a></div><div class="ttdeci">~Segment4D()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_aaa9d9c85b5c518b06d6ba58b1eef038a"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#aaa9d9c85b5c518b06d6ba58b1eef038a">NRE::Math::Segment4D::getVector</a></div><div class="ttdeci">Vector4D&lt; T &gt; getVector() const</div></div>
<div class="ttc" id="namespace_math_php"><div class="ttname"><a href="namespace_math.php">Math</a></div><div class="ttdoc">Math's API.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_ad5e7e797237e5eb4d4d9bb5e06c9f824"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#ad5e7e797237e5eb4d4d9bb5e06c9f824">NRE::Math::Segment4D::getStart</a></div><div class="ttdeci">Point4D&lt; T &gt; const  &amp; getStart() const</div></div>
<div class="ttc" id="namespacestd_php"><div class="ttname"><a href="namespacestd.php">std</a></div><div class="ttdoc">The stl standard namespace.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a3cc16c6b435ad5bdeae49572e17b7509"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a3cc16c6b435ad5bdeae49572e17b7509">NRE::Math::Segment4D::operator !=</a></div><div class="ttdeci">bool operator !=(Segment4D&lt; K &gt; const &amp;s) const</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a7b1079202714af2f32b22daf3dd24923"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a7b1079202714af2f32b22daf3dd24923">NRE::Math::Segment4D::getEnd</a></div><div class="ttdeci">Point4D&lt; T &gt; const  &amp; getEnd() const</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine's global namespace.</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a11006b9209c274c86d6cda4bd59f9404"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">NRE::Math::Segment4D::operator=</a></div><div class="ttdeci">Segment4D &amp; operator=(Segment4D const &amp;s)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_aef6aa7bce89e68ebdec107d72cbd82cd"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#aef6aa7bce89e68ebdec107d72cbd82cd">NRE::Math::Segment4D::toString</a></div><div class="ttdeci">Utility::String toString() const</div></div>
<div class="ttc" id="class_n_r_e_1_1_math_1_1_segment4_d_php_a8be047aa9307a73551d2dca7026beb8a"><div class="ttname"><a href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">NRE::Math::Segment4D::Segment4D</a></div><div class="ttdeci">Segment4D()=default</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
