<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">Matrix4x4</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::Matrix4x4&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a551309ea07648d8d0a52f9e0061e11cd">getC1</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afaadd0584eebcd6713e299d8819596a0">getC2</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a3d9902378a2bc0e10b2df0c07f75c2fa">getC3</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad4624e1695e2161c1a008676ed5761db">getC4</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abab64fd97e3718ec6b6c3153eae7e0f7">getDeterminant</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af18ca0ca5d8985baca129fa2a5fc7bb8">getL1</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a038a1b37794b229c2fbef8be54d25f37">getL2</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa8408fda644b045a014768b54ca10789">getL3</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1d6b181af872ec7c4199869cc0ced5bf">getL4</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa71e8d1336c71055bfffd646f5529e9c">IDENTITY</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae98c1b57b48fee63f21344bdac12236c">inverse</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a66fb02d3b019fea5803185179cc12d55">lookAt</a>(Vector3D&lt; K &gt; const &amp;eye, Vector3D&lt; L &gt; const &amp;center, Vector3D&lt; N &gt; const &amp;up)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a200c249276501c6536d7fa66549c616d">Matrix4x4</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#acdbcb5a6acef324ad6701c85a113f309">Matrix4x4</a>(A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m, N n, O o, P p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a08373ac6de277a4d21b6a635a4c480fa">Matrix4x4</a>(K value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a816642b426326e9c83a7d125ed542fbe">Matrix4x4</a>(Vector4D&lt; K &gt; const &amp;l1, Vector4D&lt; L &gt; const &amp;l2, Vector4D&lt; N &gt; const &amp;l3, Vector4D&lt; M &gt; const &amp;l4)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a14c6819590828c9b444f00852aea38c3">Matrix4x4</a>(Matrix4x4 const &amp;m)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a97df29fc5d305fd9b9b51196d476f935">Matrix4x4</a>(Matrix4x4 &amp;&amp;m)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a77ebe8c343e0a8733ae8b6a5ac3ad6b9">Matrix4x4</a>(Matrix3x3&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a5b0d57243d31252d9f8bc56645993e38">Matrix4x4</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ab25dbbefa3bc13a2a05b4ed53422d4e5">Matrix4x4</a>(Quaternion&lt; K &gt; const &amp;q)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#adc3426f78436370aaaac0f4cedcb4639">operator!=</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a413047372f94cee1e5bb92fb77b28709">operator*</a>(K k) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#acb00ca07056fec5a1b96eb9389965510">operator*</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a2763879aa40e5dc88829c68580c63324">operator*</a>(Vector4D&lt; K &gt; const &amp;u) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a949b6fe0630bab786fb9ccb18d40f3d9">operator*</a>(Segment4D&lt; K &gt; const &amp;s) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a811fb0a4297ef9dab8d7356ee63e0af7">operator*</a>(BezierCurve4D const &amp;c) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a9c8a248f508eb7c7d0428c186e0b197d">operator*=</a>(K k)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a6f078736bfd55662f73dc5586c137c6d">operator*=</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa227cde337fe508bfaef2301baebf22a">operator+</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7d8afa1b52432e94b6e18f12f47f1d51">operator+=</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a289112678825b775b6a98e68c4bd471c">operator-</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ac14ad0255910de41ec938ed2bb03a5c7">operator-=</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a85ae947500defeeaed75fb148dcbea27">operator/</a>(K k) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a75aff670cd84cc62ff0a81175318364c">operator/</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a13583412af93291c0d1b1b3a60984ae8">operator/=</a>(K k)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a77246318d881c54ec9a9ea03f6f0de10">operator/=</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af01dd45d74390decadb618c5c4b6c0ea">operator=</a>(Matrix4x4 const &amp;m)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af3c4b37811e643ff1fa3f1dfc8b154e1">operator=</a>(Matrix4x4 &amp;&amp;m)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a97451a508751014cf3e985984a6fbb42">operator=</a>(Matrix4x4&lt; K &gt; const &amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a2335a2e8246dfce5fd22878d77bb9c58">operator=</a>(Matrix4x4&lt; K &gt; &amp;&amp;m)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a9a4587db8dfa2f767bc2c54e9f7c8f7e">operator==</a>(Matrix4x4&lt; K &gt; const &amp;m) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#acad9523b5fc490eec219f6238fb375a2">operator[]</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae1a7d355e81500ae6901c89a6982a271">operator[]</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a37ea14eff04f9b79efc2e218fb9e9557">ortho</a>(Vector2D&lt; K &gt; const &amp;h, Vector2D&lt; L &gt; const &amp;v, Vector2D&lt; N &gt; const &amp;z)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ac9c311e86ddfd8853681456f4bc46b7a">ortho2D</a>(Vector2D&lt; K &gt; const &amp;h, Vector2D&lt; L &gt; const &amp;v)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1edb7e306457b3f1ffade48b815a2cfb">perspective</a>(Angle fov, K ratio, Vector2D&lt; L &gt; const &amp;z)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afaad6e8101614e09a677d6d329bc73ac">rotate</a>(Angle angle, Vector3D&lt; K &gt; const &amp;axis)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad6454c713aa2ab0f258b2486b7342765">scale</a>(Vector3D&lt; K &gt; const &amp;u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a005f3a836279f92372ac7179f5e6b0a1">setC1</a>(Vector4D&lt; K &gt; const &amp;c1)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afe3cec10fc0c4714765203e38f798a54">setC2</a>(Vector4D&lt; K &gt; const &amp;c2)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af07c425da2528f624e0437347ff8d5fc">setC3</a>(Vector4D&lt; K &gt; const &amp;c3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad790830fcb3da5892229975f0cb8b0c1">setC4</a>(Vector4D&lt; K &gt; const &amp;c4)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a88feb2b6536114614fa18b8169318e1d">setIdentity</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a22242cd4d4ed933b84e2a33c6e457c84">setL1</a>(Vector4D&lt; K &gt; const &amp;l1)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1c5df74c01f1622674a64dff4b674c3a">setL2</a>(Vector4D&lt; K &gt; const &amp;l2)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7ef6b7cc41ace5574268e1b015fc20da">setL3</a>(Vector4D&lt; K &gt; const &amp;l3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abf9c3d33b08e19803e3b9649c75aa8b1">setL4</a>(Vector4D&lt; K &gt; const &amp;l4)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a08213b41f6400a5b0cb359c7eff6a9ba">stretchX</a>(K u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a987a6a24b69a6ed672faf2a3038653b3">stretchY</a>(K u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae2494a3bc36e5612663939e32a74e5a6">stretchZ</a>(K u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ac3205f89b22199d53de0312232bae510">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa57ae7b2e7f570e0e1d3f1d1b5f930ca">translate</a>(Vector3D&lt; K &gt; const &amp;u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa90c64c2a18806b5bb574fce3d0af751">transpose</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aba3981af301257d2388ec5b9b8b67d0e">value</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afc73c3ace75df2dc6422a016bc4e6a2c">~Matrix4x4</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">NRE::Math::Matrix4x4&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
