<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: NRE::Math::Quaternion&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_math_1_1_quaternion-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Math::Quaternion&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A quaternion represented by a 3D rotation axis and an angle.  
 <a href="class_n_r_e_1_1_math_1_1_quaternion.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___quaternion_8hpp_source.php">NRE_Quaternion.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Math::Quaternion&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_math_1_1_quaternion.png" usemap="#NRE::Math::Quaternion_3C_20T_20_3E_map" alt=""/>
  <map id="NRE::Math::Quaternion_3C_20T_20_3E_map" name="NRE::Math::Quaternion&lt; T &gt;_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a6013b9ed2f5e3476fb47a1f02a9b7ece"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a6013b9ed2f5e3476fb47a1f02a9b7ece">Quaternion</a> ()=default</td></tr>
<tr class="separator:a6013b9ed2f5e3476fb47a1f02a9b7ece"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaaabf45cfbe6cc642ee2830c5cb0506c"><td class="memTemplParams" colspan="2">template&lt;class K , class L , class N , class M &gt; </td></tr>
<tr class="memitem:aaaabf45cfbe6cc642ee2830c5cb0506c"><td class="memTemplItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aaaabf45cfbe6cc642ee2830c5cb0506c">Quaternion</a> (K x, L y, N z, M w)</td></tr>
<tr class="separator:aaaabf45cfbe6cc642ee2830c5cb0506c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afccc9904e9be6c25f66bc5d5130da968"><td class="memTemplParams" colspan="2">template&lt;class K , class L , class N &gt; </td></tr>
<tr class="memitem:afccc9904e9be6c25f66bc5d5130da968"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afccc9904e9be6c25f66bc5d5130da968">Quaternion</a> (K x, L y, N z, Angle w)</td></tr>
<tr class="separator:afccc9904e9be6c25f66bc5d5130da968"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b09f8fc6d828b705e8cec75399992fb"><td class="memTemplParams" colspan="2">template&lt;class K , class L &gt; </td></tr>
<tr class="memitem:a9b09f8fc6d828b705e8cec75399992fb"><td class="memTemplItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9b09f8fc6d828b705e8cec75399992fb">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;ax, L an)</td></tr>
<tr class="separator:a9b09f8fc6d828b705e8cec75399992fb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2950c98333f8d8e7e7afd2fa9464189c">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;ax, Angle an)</td></tr>
<tr class="separator:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7009cc0ec7e86b7c9c65129e030d2ed3"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a7009cc0ec7e86b7c9c65129e030d2ed3">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> const &amp;q)=default</td></tr>
<tr class="separator:a7009cc0ec7e86b7c9c65129e030d2ed3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ba9e744e26455a032e87a9f155c202f"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a3ba9e744e26455a032e87a9f155c202f">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&amp;q)=default</td></tr>
<tr class="separator:a3ba9e744e26455a032e87a9f155c202f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a497a8bd5821b2bca2a3ed6cd34ff0bfd"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a497a8bd5821b2bca2a3ed6cd34ff0bfd"><td class="memTemplItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a497a8bd5821b2bca2a3ed6cd34ff0bfd">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:a497a8bd5821b2bca2a3ed6cd34ff0bfd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26b086d5b95d53024ad36e8e9141ea29"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a26b086d5b95d53024ad36e8e9141ea29">~Quaternion</a> ()=default</td></tr>
<tr class="separator:a26b086d5b95d53024ad36e8e9141ea29"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3d0e9795e471774a806dbb4db5030c4"><td class="memItemLeft" align="right" valign="top">constexpr T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af3d0e9795e471774a806dbb4db5030c4">getX</a> () const </td></tr>
<tr class="separator:af3d0e9795e471774a806dbb4db5030c4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b74222b0ad9f00b28177ac51d2931d6"><td class="memItemLeft" align="right" valign="top">constexpr T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a8b74222b0ad9f00b28177ac51d2931d6">getY</a> () const </td></tr>
<tr class="separator:a8b74222b0ad9f00b28177ac51d2931d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a93767c013073a0ee821c0690b3c08edf"><td class="memItemLeft" align="right" valign="top">constexpr T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a93767c013073a0ee821c0690b3c08edf">getZ</a> () const </td></tr>
<tr class="separator:a93767c013073a0ee821c0690b3c08edf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a87a2232db745e265d1de7b1f45ae94c3"><td class="memItemLeft" align="right" valign="top">constexpr T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a87a2232db745e265d1de7b1f45ae94c3">getW</a> () const </td></tr>
<tr class="separator:a87a2232db745e265d1de7b1f45ae94c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a783b070c5b47509f79d6b035a7b09c64"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; T &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a783b070c5b47509f79d6b035a7b09c64">getAxis</a> () const </td></tr>
<tr class="separator:a783b070c5b47509f79d6b035a7b09c64"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abd50e6dd1ef2d925315f3afcee49a522"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt; T &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#abd50e6dd1ef2d925315f3afcee49a522">getQuaternion</a> () const </td></tr>
<tr class="separator:abd50e6dd1ef2d925315f3afcee49a522"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b69e61734bcb338d4f30e9332927c7f"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a9b69e61734bcb338d4f30e9332927c7f"><td class="memTemplItemLeft" align="right" valign="top">constexpr void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9b69e61734bcb338d4f30e9332927c7f">setX</a> (K x)</td></tr>
<tr class="separator:a9b69e61734bcb338d4f30e9332927c7f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aea09f7397244457d1ac93b544752af74"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:aea09f7397244457d1ac93b544752af74"><td class="memTemplItemLeft" align="right" valign="top">constexpr void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aea09f7397244457d1ac93b544752af74">setY</a> (K y)</td></tr>
<tr class="separator:aea09f7397244457d1ac93b544752af74"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2cb08d334a509dee9f157604fc8cc552"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a2cb08d334a509dee9f157604fc8cc552"><td class="memTemplItemLeft" align="right" valign="top">constexpr void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2cb08d334a509dee9f157604fc8cc552">setZ</a> (K z)</td></tr>
<tr class="separator:a2cb08d334a509dee9f157604fc8cc552"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa558dd0fc08159836151b498ea670812"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:aa558dd0fc08159836151b498ea670812"><td class="memTemplItemLeft" align="right" valign="top">constexpr void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa558dd0fc08159836151b498ea670812">setW</a> (K w)</td></tr>
<tr class="separator:aa558dd0fc08159836151b498ea670812"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae1c53a59d250b7fb7d62437fa2625073"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:ae1c53a59d250b7fb7d62437fa2625073"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae1c53a59d250b7fb7d62437fa2625073">setAngleAxis</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;axis, Angle w)</td></tr>
<tr class="separator:ae1c53a59d250b7fb7d62437fa2625073"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa2fe3982d5a5f0c86513c8bd6cf0158c"><td class="memItemLeft" align="right" valign="top">constexpr void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa2fe3982d5a5f0c86513c8bd6cf0158c">setIdentity</a> ()</td></tr>
<tr class="separator:aa2fe3982d5a5f0c86513c8bd6cf0158c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2b4dc46655e5101cf571c2a9709592a"><td class="memItemLeft" align="right" valign="top">long double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac2b4dc46655e5101cf571c2a9709592a">norm</a> () const </td></tr>
<tr class="separator:ac2b4dc46655e5101cf571c2a9709592a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91ff4992c42b3498a70a79099c58d9ce"><td class="memItemLeft" align="right" valign="top">constexpr T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a91ff4992c42b3498a70a79099c58d9ce">normSquared</a> () const </td></tr>
<tr class="separator:a91ff4992c42b3498a70a79099c58d9ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac60e647be1fb50481cd5813f1f0489d0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac60e647be1fb50481cd5813f1f0489d0">normalize</a> ()</td></tr>
<tr class="separator:ac60e647be1fb50481cd5813f1f0489d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75d720a0a4012f26413831d874124793"><td class="memItemLeft" align="right" valign="top">constexpr const T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a75d720a0a4012f26413831d874124793">value</a> () const </td></tr>
<tr class="separator:a75d720a0a4012f26413831d874124793"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a35aa40cb7c94b4f6be4bb8929e197873"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a35aa40cb7c94b4f6be4bb8929e197873">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> const &amp;q)=default</td></tr>
<tr class="separator:a35aa40cb7c94b4f6be4bb8929e197873"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e071531517e1d0ef20b0e2150a0e4df"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a7e071531517e1d0ef20b0e2150a0e4df">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&amp;q)=default</td></tr>
<tr class="separator:a7e071531517e1d0ef20b0e2150a0e4df"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a79002ab3c3e55c8f06f82a73127d710d"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a79002ab3c3e55c8f06f82a73127d710d"><td class="memTemplItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a79002ab3c3e55c8f06f82a73127d710d">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:a79002ab3c3e55c8f06f82a73127d710d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ac5b0d660ddb2ef7b90937a4a8d9839"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a9ac5b0d660ddb2ef7b90937a4a8d9839"><td class="memTemplItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9ac5b0d660ddb2ef7b90937a4a8d9839">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; &amp;&amp;q)</td></tr>
<tr class="separator:a9ac5b0d660ddb2ef7b90937a4a8d9839"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05b939c554b2df822af9cccc17dd53ad"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a05b939c554b2df822af9cccc17dd53ad"><td class="memTemplItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a05b939c554b2df822af9cccc17dd53ad">operator*=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:a05b939c554b2df822af9cccc17dd53ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac60993416cedbf373a7dfaa9bcc582fc"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:ac60993416cedbf373a7dfaa9bcc582fc"><td class="memTemplItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; std::common_type_t&lt; T, K &gt; &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac60993416cedbf373a7dfaa9bcc582fc">operator*</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q) const </td></tr>
<tr class="separator:ac60993416cedbf373a7dfaa9bcc582fc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6b212d1f08fc9a5935bd323b22b9c531"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a6b212d1f08fc9a5935bd323b22b9c531">toString</a> () const </td></tr>
<tr class="separator:a6b212d1f08fc9a5935bd323b22b9c531"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::Math::Quaternion&lt; T &gt;</h3>

<p>A quaternion represented by a 3D rotation axis and an angle. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a6013b9ed2f5e3476fb47a1f02a9b7ece"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The internal quaternion Construct the identity quaternion </p>

</div>
</div>
<a class="anchor" id="aaaabf45cfbe6cc642ee2830c5cb0506c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L , class N , class M &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">N&#160;</td>
          <td class="paramname"><em>z</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">M&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion with direct assignment </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the x coordinate </td></tr>
    <tr><td class="paramname">y</td><td>the y coordinate </td></tr>
    <tr><td class="paramname">z</td><td>the z coordinate </td></tr>
    <tr><td class="paramname">w</td><td>the w coordinate </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="afccc9904e9be6c25f66bc5d5130da968"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L , class N &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">N&#160;</td>
          <td class="paramname"><em>z</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion from angle-axis construction </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the x coordinate </td></tr>
    <tr><td class="paramname">y</td><td>the y coordinate </td></tr>
    <tr><td class="paramname">z</td><td>the z coordinate </td></tr>
    <tr><td class="paramname">w</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9b09f8fc6d828b705e8cec75399992fb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>ax</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>an</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion with direct assignment </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ax</td><td>the rotation's axis </td></tr>
    <tr><td class="paramname">an</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2950c98333f8d8e7e7afd2fa9464189c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>ax</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>an</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion from angle-axis construction </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ax</td><td>the rotation's axis </td></tr>
    <tr><td class="paramname">an</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7009cc0ec7e86b7c9c65129e030d2ed3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3ba9e744e26455a032e87a9f155c202f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a497a8bd5821b2bca2a3ed6cd34ff0bfd"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert a K-type quaternion into a T-type quaternion </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the K-type quaternion to convert </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a26b086d5b95d53024ad36e8e9141ea29"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php" title="A quaternion represented by a 3D rotation axis and an angle. ">Quaternion</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a783b070c5b47509f79d6b035a7b09c64"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt;T&gt; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getAxis </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the rotation's axis </dd></dl>

</div>
</div>
<a class="anchor" id="abd50e6dd1ef2d925315f3afcee49a522"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt;T&gt; const&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getQuaternion </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal quaternion </dd></dl>

</div>
</div>
<a class="anchor" id="a87a2232db745e265d1de7b1f45ae94c3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getW </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the w value </dd></dl>

</div>
</div>
<a class="anchor" id="af3d0e9795e471774a806dbb4db5030c4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getX </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the x value </dd></dl>

</div>
</div>
<a class="anchor" id="a8b74222b0ad9f00b28177ac51d2931d6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getY </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the y value </dd></dl>

</div>
</div>
<a class="anchor" id="a93767c013073a0ee821c0690b3c08edf"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getZ </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the z value </dd></dl>

</div>
</div>
<a class="anchor" id="ac2b4dc46655e5101cf571c2a9709592a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">long double <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::norm </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the quaternion's norm </dd></dl>

</div>
</div>
<a class="anchor" id="ac60e647be1fb50481cd5813f1f0489d0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::normalize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Normalize the quaternion </p>

</div>
</div>
<a class="anchor" id="a91ff4992c42b3498a70a79099c58d9ce"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::normSquared </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the squared quaternion's norm </dd></dl>

</div>
</div>
<a class="anchor" id="ac60993416cedbf373a7dfaa9bcc582fc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt;std::common_type_t&lt;T, K&gt; &gt; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator* </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the quaternion resulting in the multiplication of this and q </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the second quaternion </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the computed quaternion </dd></dl>

</div>
</div>
<a class="anchor" id="a05b939c554b2df822af9cccc17dd53ad"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator*= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Multiply 2 quaternions together </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the second quaternion </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a35aa40cb7c94b4f6be4bb8929e197873"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a7e071531517e1d0ef20b0e2150a0e4df"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a79002ab3c3e55c8f06f82a73127d710d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a9ac5b0d660ddb2ef7b90937a4a8d9839"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ae1c53a59d250b7fb7d62437fa2625073"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setAngleAxis </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>axis</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Angle axis setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">axis</td><td>the new rotation's axis </td></tr>
    <tr><td class="paramname">w</td><td>the new rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aa2fe3982d5a5f0c86513c8bd6cf0158c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setIdentity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the quaternion to the identity quaternion </p>

</div>
</div>
<a class="anchor" id="aa558dd0fc08159836151b498ea670812"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setW </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>W setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the new value for w </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9b69e61734bcb338d4f30e9332927c7f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setX </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>X setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the new value for x </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aea09f7397244457d1ac93b544752af74"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setY </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>y</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Y setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">y</td><td>the new value for y </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2cb08d334a509dee9f157604fc8cc552"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setZ </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>z</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Z setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">z</td><td>the new value for z </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6b212d1f08fc9a5935bd323b22b9c531"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">Utility::String <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the quaternion into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted quaternion </dd></dl>

</div>
</div>
<a class="anchor" id="a75d720a0a4012f26413831d874124793"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr const T* <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::value </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a pointer to the quaternion's data </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Math/src/Math/Matrix/4D/<a class="el" href="_n_r_e___matrix4x4_8hpp_source.php">NRE_Matrix4x4.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Math/src/Math/Quaternion/<a class="el" href="_n_r_e___quaternion_8hpp_source.php">NRE_Quaternion.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
