<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">BezierCurve4D</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::BezierCurve4D Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac2c5db9079a354e315a9791e605a4c0f">BezierCurve4D</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a2d7167d43835fa7e59aa1686fc60491d">BezierCurve4D</a>(std::initializer_list&lt; Point4D&lt; float &gt;&gt; points)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a07cfaa85fe7f01978df90cc5d8da7745">BezierCurve4D</a>(Utility::Vector&lt; Point4D&lt; float &gt;&gt; &amp;&amp;c)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a3bbc56639ece56d58142fda5f4c88a7e">BezierCurve4D</a>(BezierCurve4D const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a9419cba1c0b449ec3e007cd781850aa8">BezierCurve4D</a>(BezierCurve4D &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#af8ace4b3107b7a451b393f7cd096d64a">getPoint</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ae5fcb54b717ecb456024df099a36f6f6">getSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">operator=</a>(BezierCurve4D const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a732355f50b5b5fd92b131bbc3a315232">operator=</a>(BezierCurve4D &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ae7a66dd96aa0615bc4d6c04dde61d83a">operator[]</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#aa1c7c91ef3273975336944d8647a808f">operator[]</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ae329cb8195c2e84597f8dcaf631b2c6d">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a55cf4d9eff91a6895acb187e2414bfa8">~BezierCurve4D</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php">NRE::Math::BezierCurve4D</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
