<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: NRE::Math::Quaternion&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_math_1_1_quaternion-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Math::Quaternion&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A quaternion represented by a 3D rotation axis and an angle.  
 <a href="class_n_r_e_1_1_math_1_1_quaternion.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___quaternion_8hpp_source.php">NRE_Quaternion.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Math::Quaternion&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_math_1_1_quaternion.png" alt=""/>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a3f449cc3a127a054397bf884c2c02612"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a3f449cc3a127a054397bf884c2c02612">Quaternion</a> ()=default</td></tr>
<tr class="separator:a3f449cc3a127a054397bf884c2c02612"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae8a7f78b4e1a771ccf206d2bb88fe55d"><td class="memTemplParams" colspan="2">template&lt;class K , class L , class N , class M &gt; </td></tr>
<tr class="memitem:ae8a7f78b4e1a771ccf206d2bb88fe55d"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae8a7f78b4e1a771ccf206d2bb88fe55d">Quaternion</a> (K x, L y, N z, M w)</td></tr>
<tr class="separator:ae8a7f78b4e1a771ccf206d2bb88fe55d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afccc9904e9be6c25f66bc5d5130da968"><td class="memTemplParams" colspan="2">template&lt;class K , class L , class N &gt; </td></tr>
<tr class="memitem:afccc9904e9be6c25f66bc5d5130da968"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afccc9904e9be6c25f66bc5d5130da968">Quaternion</a> (K x, L y, N z, Angle w)</td></tr>
<tr class="separator:afccc9904e9be6c25f66bc5d5130da968"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afdefc312e78b38dabedb3fc06820b1c2"><td class="memTemplParams" colspan="2">template&lt;class K , class L &gt; </td></tr>
<tr class="memitem:afdefc312e78b38dabedb3fc06820b1c2"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afdefc312e78b38dabedb3fc06820b1c2">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;ax, L an)</td></tr>
<tr class="separator:afdefc312e78b38dabedb3fc06820b1c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2950c98333f8d8e7e7afd2fa9464189c">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;ax, Angle an)</td></tr>
<tr class="separator:a2950c98333f8d8e7e7afd2fa9464189c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af61e50f88ea8d2a46711f9ce3bd7973e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af61e50f88ea8d2a46711f9ce3bd7973e">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> const &amp;q)=default</td></tr>
<tr class="separator:af61e50f88ea8d2a46711f9ce3bd7973e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a46c68b3cdaa31978909ce33f9594892d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a46c68b3cdaa31978909ce33f9594892d">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&amp;q)=default</td></tr>
<tr class="separator:a46c68b3cdaa31978909ce33f9594892d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18b3f43d80e22c9c52b1af98a80be7b4"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a18b3f43d80e22c9c52b1af98a80be7b4"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a18b3f43d80e22c9c52b1af98a80be7b4">Quaternion</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:a18b3f43d80e22c9c52b1af98a80be7b4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26b086d5b95d53024ad36e8e9141ea29"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a26b086d5b95d53024ad36e8e9141ea29">~Quaternion</a> ()=default</td></tr>
<tr class="separator:a26b086d5b95d53024ad36e8e9141ea29"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac3fd3244b84988582c52737d5657685a"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac3fd3244b84988582c52737d5657685a">getX</a> () const</td></tr>
<tr class="separator:ac3fd3244b84988582c52737d5657685a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a68dbcdfac818a38e44646633c83978db"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a68dbcdfac818a38e44646633c83978db">getY</a> () const</td></tr>
<tr class="separator:a68dbcdfac818a38e44646633c83978db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a22494c74ff791a1d62dd19e2d822435c"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a22494c74ff791a1d62dd19e2d822435c">getZ</a> () const</td></tr>
<tr class="separator:a22494c74ff791a1d62dd19e2d822435c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2a8ede83e9fdee10a3b90f73d78be78"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac2a8ede83e9fdee10a3b90f73d78be78">getW</a> () const</td></tr>
<tr class="separator:ac2a8ede83e9fdee10a3b90f73d78be78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c31f1d471ce1a853e4c3e9eeb818a7e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; T &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a0c31f1d471ce1a853e4c3e9eeb818a7e">getAxis</a> () const</td></tr>
<tr class="separator:a0c31f1d471ce1a853e4c3e9eeb818a7e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeccb2a1b8464b0815546ce4fb0bf58a4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt; T &gt; const  &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aeccb2a1b8464b0815546ce4fb0bf58a4">getQuaternion</a> () const</td></tr>
<tr class="separator:aeccb2a1b8464b0815546ce4fb0bf58a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:affd206d7637a82777bd2d5317f432068"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:affd206d7637a82777bd2d5317f432068"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#affd206d7637a82777bd2d5317f432068">setX</a> (K x)</td></tr>
<tr class="separator:affd206d7637a82777bd2d5317f432068"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9c3b2a87afe4f292a3516520a205422f"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a9c3b2a87afe4f292a3516520a205422f"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9c3b2a87afe4f292a3516520a205422f">setY</a> (K y)</td></tr>
<tr class="separator:a9c3b2a87afe4f292a3516520a205422f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05d28d525f52e96129de19ca171a327e"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a05d28d525f52e96129de19ca171a327e"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a05d28d525f52e96129de19ca171a327e">setZ</a> (K z)</td></tr>
<tr class="separator:a05d28d525f52e96129de19ca171a327e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac0f84c92e58d56505375a990ba916d0"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:aac0f84c92e58d56505375a990ba916d0"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aac0f84c92e58d56505375a990ba916d0">setW</a> (K w)</td></tr>
<tr class="separator:aac0f84c92e58d56505375a990ba916d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae1c53a59d250b7fb7d62437fa2625073"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:ae1c53a59d250b7fb7d62437fa2625073"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae1c53a59d250b7fb7d62437fa2625073">setAngleAxis</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;axis, Angle w)</td></tr>
<tr class="separator:ae1c53a59d250b7fb7d62437fa2625073"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06ead9af6d624c1572b219a5a1825ce7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">setIdentity</a> ()</td></tr>
<tr class="separator:a06ead9af6d624c1572b219a5a1825ce7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa6f362c4d49fa683ce2144341e4762f9"><td class="memItemLeft" align="right" valign="top">long double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa6f362c4d49fa683ce2144341e4762f9">norm</a> () const</td></tr>
<tr class="separator:aa6f362c4d49fa683ce2144341e4762f9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af73f7347ac757f79f7e221a1e79f7b5e"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af73f7347ac757f79f7e221a1e79f7b5e">normSquared</a> () const</td></tr>
<tr class="separator:af73f7347ac757f79f7e221a1e79f7b5e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9361a0a54041ad7cf5d0bb706819b909"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9361a0a54041ad7cf5d0bb706819b909">normalize</a> ()</td></tr>
<tr class="separator:a9361a0a54041ad7cf5d0bb706819b909"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28c0a2093a60c84e79bfa7352ec3599d"><td class="memItemLeft" align="right" valign="top">const T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a28c0a2093a60c84e79bfa7352ec3599d">value</a> () const</td></tr>
<tr class="separator:a28c0a2093a60c84e79bfa7352ec3599d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a302245476a19a35d788e0959ce700028"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a302245476a19a35d788e0959ce700028">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> const &amp;q)=default</td></tr>
<tr class="separator:a302245476a19a35d788e0959ce700028"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a78d3fafa8fb5345c20e6540bfa4835b7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a78d3fafa8fb5345c20e6540bfa4835b7">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&amp;q)=default</td></tr>
<tr class="separator:a78d3fafa8fb5345c20e6540bfa4835b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac567afb3fb86f4233db1078d8f955dc8"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:ac567afb3fb86f4233db1078d8f955dc8"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac567afb3fb86f4233db1078d8f955dc8">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:ac567afb3fb86f4233db1078d8f955dc8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afde645a57daee9b9849b085c5fa3f3d4"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:afde645a57daee9b9849b085c5fa3f3d4"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afde645a57daee9b9849b085c5fa3f3d4">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; &amp;&amp;q)</td></tr>
<tr class="separator:afde645a57daee9b9849b085c5fa3f3d4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae75df23bed763e5d87dcb80d1b6cb1b8"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:ae75df23bed763e5d87dcb80d1b6cb1b8"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae75df23bed763e5d87dcb80d1b6cb1b8">operator *=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q)</td></tr>
<tr class="separator:ae75df23bed763e5d87dcb80d1b6cb1b8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9d7b703ea6c6d7a8e6f2bcc949f54774"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a9d7b703ea6c6d7a8e6f2bcc949f54774"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; std::common_type_t&lt; T, K &gt; &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9d7b703ea6c6d7a8e6f2bcc949f54774">operator *</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;q) const</td></tr>
<tr class="separator:a9d7b703ea6c6d7a8e6f2bcc949f54774"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8823422d6e88e707e6c3882692f365b"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac8823422d6e88e707e6c3882692f365b">toString</a> () const</td></tr>
<tr class="separator:ac8823422d6e88e707e6c3882692f365b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::Math::Quaternion&lt; T &gt;</h3>

<p>A quaternion represented by a 3D rotation axis and an angle. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a3f449cc3a127a054397bf884c2c02612"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3f449cc3a127a054397bf884c2c02612">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[1/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The internal quaternion Construct the identity quaternion </p>

</div>
</div>
<a id="ae8a7f78b4e1a771ccf206d2bb88fe55d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae8a7f78b4e1a771ccf206d2bb88fe55d">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[2/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L , class N , class M &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">N&#160;</td>
          <td class="paramname"><em>z</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">M&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion with direct assignment </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the x coordinate </td></tr>
    <tr><td class="paramname">y</td><td>the y coordinate </td></tr>
    <tr><td class="paramname">z</td><td>the z coordinate </td></tr>
    <tr><td class="paramname">w</td><td>the w coordinate </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="afccc9904e9be6c25f66bc5d5130da968"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afccc9904e9be6c25f66bc5d5130da968">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[3/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L , class N &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>y</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">N&#160;</td>
          <td class="paramname"><em>z</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion from angle-axis construction </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the x coordinate </td></tr>
    <tr><td class="paramname">y</td><td>the y coordinate </td></tr>
    <tr><td class="paramname">z</td><td>the z coordinate </td></tr>
    <tr><td class="paramname">w</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="afdefc312e78b38dabedb3fc06820b1c2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afdefc312e78b38dabedb3fc06820b1c2">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[4/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>ax</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>an</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion with direct assignment </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ax</td><td>the rotation's axis </td></tr>
    <tr><td class="paramname">an</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a2950c98333f8d8e7e7afd2fa9464189c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2950c98333f8d8e7e7afd2fa9464189c">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[5/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>ax</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>an</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a quaternion from angle-axis construction </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ax</td><td>the rotation's axis </td></tr>
    <tr><td class="paramname">an</td><td>the rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="af61e50f88ea8d2a46711f9ce3bd7973e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af61e50f88ea8d2a46711f9ce3bd7973e">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[6/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a46c68b3cdaa31978909ce33f9594892d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a46c68b3cdaa31978909ce33f9594892d">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[7/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a18b3f43d80e22c9c52b1af98a80be7b4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a18b3f43d80e22c9c52b1af98a80be7b4">&#9670;&nbsp;</a></span>Quaternion() <span class="overload">[8/8]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert a K-type quaternion into a T-type quaternion </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the K-type quaternion to convert </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a26b086d5b95d53024ad36e8e9141ea29"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a26b086d5b95d53024ad36e8e9141ea29">&#9670;&nbsp;</a></span>~Quaternion()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php" title="A quaternion represented by a 3D rotation axis and an angle.">Quaternion</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a0c31f1d471ce1a853e4c3e9eeb818a7e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0c31f1d471ce1a853e4c3e9eeb818a7e">&#9670;&nbsp;</a></span>getAxis()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt;T&gt; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getAxis </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the rotation's axis </dd></dl>

</div>
</div>
<a id="aeccb2a1b8464b0815546ce4fb0bf58a4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aeccb2a1b8464b0815546ce4fb0bf58a4">&#9670;&nbsp;</a></span>getQuaternion()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt;T&gt; const&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getQuaternion </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal quaternion </dd></dl>

</div>
</div>
<a id="ac2a8ede83e9fdee10a3b90f73d78be78"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac2a8ede83e9fdee10a3b90f73d78be78">&#9670;&nbsp;</a></span>getW()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getW </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the w value </dd></dl>

</div>
</div>
<a id="ac3fd3244b84988582c52737d5657685a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac3fd3244b84988582c52737d5657685a">&#9670;&nbsp;</a></span>getX()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getX </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the x value </dd></dl>

</div>
</div>
<a id="a68dbcdfac818a38e44646633c83978db"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a68dbcdfac818a38e44646633c83978db">&#9670;&nbsp;</a></span>getY()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getY </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the y value </dd></dl>

</div>
</div>
<a id="a22494c74ff791a1d62dd19e2d822435c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a22494c74ff791a1d62dd19e2d822435c">&#9670;&nbsp;</a></span>getZ()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::getZ </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the z value </dd></dl>

</div>
</div>
<a id="aa6f362c4d49fa683ce2144341e4762f9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa6f362c4d49fa683ce2144341e4762f9">&#9670;&nbsp;</a></span>norm()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">long double <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::norm </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the quaternion's norm </dd></dl>

</div>
</div>
<a id="a9361a0a54041ad7cf5d0bb706819b909"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9361a0a54041ad7cf5d0bb706819b909">&#9670;&nbsp;</a></span>normalize()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::normalize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Normalize the quaternion </p>

</div>
</div>
<a id="af73f7347ac757f79f7e221a1e79f7b5e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af73f7347ac757f79f7e221a1e79f7b5e">&#9670;&nbsp;</a></span>normSquared()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::normSquared </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the squared quaternion's norm </dd></dl>

</div>
</div>
<a id="a9d7b703ea6c6d7a8e6f2bcc949f54774"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9d7b703ea6c6d7a8e6f2bcc949f54774">&#9670;&nbsp;</a></span>operator *()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt;std::common_type_t&lt;T, K&gt; &gt; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator * </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the quaternion resulting in the multiplication of this and q </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the second quaternion </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the computed quaternion </dd></dl>

</div>
</div>
<a id="ae75df23bed763e5d87dcb80d1b6cb1b8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae75df23bed763e5d87dcb80d1b6cb1b8">&#9670;&nbsp;</a></span>operator *=()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator *= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Multiply 2 quaternions together </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the second quaternion </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="a302245476a19a35d788e0959ce700028"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a302245476a19a35d788e0959ce700028">&#9670;&nbsp;</a></span>operator=() <span class="overload">[1/4]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="a78d3fafa8fb5345c20e6540bfa4835b7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a78d3fafa8fb5345c20e6540bfa4835b7">&#9670;&nbsp;</a></span>operator=() <span class="overload">[2/4]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="ac567afb3fb86f4233db1078d8f955dc8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac567afb3fb86f4233db1078d8f955dc8">&#9670;&nbsp;</a></span>operator=() <span class="overload">[3/4]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="afde645a57daee9b9849b085c5fa3f3d4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afde645a57daee9b9849b085c5fa3f3d4">&#9670;&nbsp;</a></span>operator=() <span class="overload">[4/4]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a>&lt; K &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>q</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move q into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">q</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="ae1c53a59d250b7fb7d62437fa2625073"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae1c53a59d250b7fb7d62437fa2625073">&#9670;&nbsp;</a></span>setAngleAxis()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setAngleAxis </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>axis</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>w</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Angle axis setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">axis</td><td>the new rotation's axis </td></tr>
    <tr><td class="paramname">w</td><td>the new rotation's angle </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a06ead9af6d624c1572b219a5a1825ce7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a06ead9af6d624c1572b219a5a1825ce7">&#9670;&nbsp;</a></span>setIdentity()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setIdentity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the quaternion to the identity quaternion </p>

</div>
</div>
<a id="aac0f84c92e58d56505375a990ba916d0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aac0f84c92e58d56505375a990ba916d0">&#9670;&nbsp;</a></span>setW()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setW </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>W setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the new value for w </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="affd206d7637a82777bd2d5317f432068"></a>
<h2 class="memtitle"><span class="permalink"><a href="#affd206d7637a82777bd2d5317f432068">&#9670;&nbsp;</a></span>setX()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setX </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>x</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>X setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">x</td><td>the new value for x </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a9c3b2a87afe4f292a3516520a205422f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9c3b2a87afe4f292a3516520a205422f">&#9670;&nbsp;</a></span>setY()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setY </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>y</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Y setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">y</td><td>the new value for y </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a05d28d525f52e96129de19ca171a327e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a05d28d525f52e96129de19ca171a327e">&#9670;&nbsp;</a></span>setZ()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::setZ </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>z</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Z setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">z</td><td>the new value for z </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="ac8823422d6e88e707e6c3882692f365b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac8823422d6e88e707e6c3882692f365b">&#9670;&nbsp;</a></span>toString()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">Utility::String <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the quaternion into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted quaternion </dd></dl>

</div>
</div>
<a id="a28c0a2093a60c84e79bfa7352ec3599d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a28c0a2093a60c84e79bfa7352ec3599d">&#9670;&nbsp;</a></span>value()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const T* <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion</a>&lt; T &gt;::value </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a pointer to the quaternion's data </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Matrix/4D/<a class="el" href="_n_r_e___matrix4x4_8hpp_source.php">NRE_Matrix4x4.hpp</a></li>
<li>C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Quaternion/<a class="el" href="_n_r_e___quaternion_8hpp_source.php">NRE_Quaternion.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
