<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">Plane</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::Plane&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a33aacb5cafdabacc3cd770bcf9cd59ba">distance</a>(Point4D&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a99223b6faf67f270c51c8361951e93f3">distance</a>(Point3D&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aedde72678d5e2d8f2ae5d1ae184387c9">getNormal</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a46276cd4adb703a1d2660dd3749da009">getPoint</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aaf833cb53bd5e8136cf31cc16a0bb9de">operator!=</a>(Plane&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a40cd036f8594f8ee92b0a3aef9a37b4b">operator=</a>(Plane const &amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a35d22a47dc2027f8bad8cd7402cd8b76">operator=</a>(Plane &amp;&amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a637c45472eba9f3716358336c2dc3910">operator=</a>(Plane&lt; K &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac7691d868425f12e7667c0e2b82a4474">operator=</a>(Plane&lt; K &gt; &amp;&amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aafd5fc88fc91e021e57970c62f041e3c">operator==</a>(Plane&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#af2054e2cb1b34e40c774630369fe00cd">Plane</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a6c014ce936660bb02fc14d56b3b5bf86">Plane</a>(Vector4D&lt; K &gt; const &amp;n, Point4D&lt; L &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a4135293d0d7a5a39460298f9c4dd1fcc">Plane</a>(Vector3D&lt; K &gt; const &amp;n, Point3D&lt; L &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ad4191d3e41d276134dcd360bab0b4f2d">Plane</a>(Point4D&lt; K &gt; const &amp;p1, Point4D&lt; L &gt; const &amp;p2, Point4D&lt; N &gt; const &amp;p3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ae21c13787931464be7f42712bbb89006">Plane</a>(Point3D&lt; K &gt; const &amp;p1, Point3D&lt; L &gt; const &amp;p2, Point3D&lt; N &gt; const &amp;p3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#af2b9e5f0f2973d92440f6b1425f60b47">Plane</a>(Plane const &amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a473da87d9670f46e8b5017468128d666">Plane</a>(Plane &amp;&amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a02e1d7da15ab769cb1075958092ea05f">Plane</a>(Plane&lt; K &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a6c6bbe5dbc3df0fce4c4baa9d249e307">setNormal</a>(Vector4D&lt; K &gt; const &amp;n)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac9d2733e98125eed3250bfa94bea8208">setNormal</a>(Vector3D&lt; K &gt; const &amp;n)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a834bd4f96aa5f294dc53769897f86faf">setNormalAndPoint</a>(Vector4D&lt; K &gt; const &amp;n, Point4D&lt; L &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a1050a631b735c2134234d6976f12d643">setNormalAndPoint</a>(Vector3D&lt; K &gt; const &amp;n, Point3D&lt; L &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a1a1399fdd0b69e00cd99e060827c84e8">setPoint</a>(Point4D&lt; K &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a9d07960fc8556682755732bd7271c240">setPoint</a>(Point3D&lt; K &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a6ac54819f460bf94e5be07455b54058f">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a82e7af5642281d56674ecf427a3e5311">~Plane</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
