<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">BezierCurve3D</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::BezierCurve3D Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ae9834d919c43211705a9ab9fd10dea1d">BezierCurve3D</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a86e23312e33c11a5dd96fa23ef5faeeb">BezierCurve3D</a>(std::initializer_list&lt; Point3D&lt; float &gt;&gt; points)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a862ab044f5cac6e196a5e8b492727e23">BezierCurve3D</a>(Utility::Vector&lt; Point3D&lt; float &gt;&gt; &amp;&amp;c)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ad139d982bb6c0f79dfeca7dcf06393f7">BezierCurve3D</a>(BezierCurve3D const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a8383e094e83d4a3d8c75f415fc3de876">BezierCurve3D</a>(BezierCurve3D &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#afd89fa3c2448a334c6cda56e044bf932">getPoint</a>(std::size_t index) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a8c90a8e4e0f3da2823118c9a7095f2ec">getSize</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ad5650e22699bb679f27f87388a9c3a7b">operator []</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a9ccb1819b0329aceeb82d70fd90a1ed2">operator []</a>(std::size_t index) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a4dac44314e1e432b221b1b3b11b2d825">operator=</a>(BezierCurve3D const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a2b04688e57f83fb55ed0cba0adbbcc0e">operator=</a>(BezierCurve3D &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a1bc36be181346d58aafad791dee42d0f">toString</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#aad296197dfdc4bfc860d3a2c332def39">~BezierCurve3D</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php">NRE::Math::BezierCurve3D</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
