<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">Quaternion</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::Quaternion&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a0c31f1d471ce1a853e4c3e9eeb818a7e">getAxis</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aeccb2a1b8464b0815546ce4fb0bf58a4">getQuaternion</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac2a8ede83e9fdee10a3b90f73d78be78">getW</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac3fd3244b84988582c52737d5657685a">getX</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a68dbcdfac818a38e44646633c83978db">getY</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a22494c74ff791a1d62dd19e2d822435c">getZ</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa6f362c4d49fa683ce2144341e4762f9">norm</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9361a0a54041ad7cf5d0bb706819b909">normalize</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af73f7347ac757f79f7e221a1e79f7b5e">normSquared</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9d7b703ea6c6d7a8e6f2bcc949f54774">operator *</a>(Quaternion&lt; K &gt; const &amp;q) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae75df23bed763e5d87dcb80d1b6cb1b8">operator *=</a>(Quaternion&lt; K &gt; const &amp;q)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a302245476a19a35d788e0959ce700028">operator=</a>(Quaternion const &amp;q)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a78d3fafa8fb5345c20e6540bfa4835b7">operator=</a>(Quaternion &amp;&amp;q)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac567afb3fb86f4233db1078d8f955dc8">operator=</a>(Quaternion&lt; K &gt; const &amp;q)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afde645a57daee9b9849b085c5fa3f3d4">operator=</a>(Quaternion&lt; K &gt; &amp;&amp;q)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a3f449cc3a127a054397bf884c2c02612">Quaternion</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae8a7f78b4e1a771ccf206d2bb88fe55d">Quaternion</a>(K x, L y, N z, M w)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afccc9904e9be6c25f66bc5d5130da968">Quaternion</a>(K x, L y, N z, Angle w)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#afdefc312e78b38dabedb3fc06820b1c2">Quaternion</a>(Vector3D&lt; K &gt; const &amp;ax, L an)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2950c98333f8d8e7e7afd2fa9464189c">Quaternion</a>(Vector3D&lt; K &gt; const &amp;ax, Angle an)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af61e50f88ea8d2a46711f9ce3bd7973e">Quaternion</a>(Quaternion const &amp;q)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a46c68b3cdaa31978909ce33f9594892d">Quaternion</a>(Quaternion &amp;&amp;q)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a18b3f43d80e22c9c52b1af98a80be7b4">Quaternion</a>(Quaternion&lt; K &gt; const &amp;q)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae1c53a59d250b7fb7d62437fa2625073">setAngleAxis</a>(Vector3D&lt; K &gt; const &amp;axis, Angle w)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">setIdentity</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aac0f84c92e58d56505375a990ba916d0">setW</a>(K w)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#affd206d7637a82777bd2d5317f432068">setX</a>(K x)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9c3b2a87afe4f292a3516520a205422f">setY</a>(K y)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a05d28d525f52e96129de19ca171a327e">setZ</a>(K z)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac8823422d6e88e707e6c3882692f365b">toString</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a28c0a2093a60c84e79bfa7352ec3599d">value</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a26b086d5b95d53024ad36e8e9141ea29">~Quaternion</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php">NRE::Math::Quaternion&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
