<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">Plane</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::Plane&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#acbc29f00652a75c55e616393c7683884">distance</a>(Point4D&lt; T &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac7d06c9e2837368133d54cb7dee83bf1">distance</a>(Point3D&lt; T &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a79d1c2c300ffd46fe05b3db73d3ba5e9">getNormal</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a03a5de5fa4540d7d5c10ade7699b6dd6">getPoint</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a58a5d713ef0706697e553d02e762b5d9">operator!=</a>(Plane&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aff4e35b9d557e9be76a2704d3b4a62c9">operator=</a>(Plane const &amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a22483fc71c8ae538368fbf58d489cb86">operator=</a>(Plane &amp;&amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a8d53debe9351959bc35c52a1e91702be">operator==</a>(Plane&lt; K &gt; const &amp;p) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac1cc30c8490ffe79f4f68dfbf1f0054b">Plane</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aa2e856cc13858169dbb76dab12038e82">Plane</a>(Vector4D&lt; T &gt; const &amp;n, Point4D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a388024d654ae5292bbb0b3fd6aadc9cc">Plane</a>(Vector3D&lt; T &gt; const &amp;n, Point3D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a39b5bc2cfba5d27f4b822c19c3683043">Plane</a>(Point4D&lt; T &gt; const &amp;p1, Point4D&lt; T &gt; const &amp;p2, Point4D&lt; T &gt; const &amp;p3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac40ab43a421db9b5a167a04c29c32df9">Plane</a>(Point3D&lt; T &gt; const &amp;p1, Point3D&lt; T &gt; const &amp;p2, Point3D&lt; T &gt; const &amp;p3)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aee8fa619669ccb47094e8be78283d357">Plane</a>(Plane const &amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a881c4388de2120d9f5f660e6825436e5">Plane</a>(Plane &amp;&amp;p)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac203a7e69af509433373854a654355d4">Plane</a>(Plane&lt; K &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a5d8b503157d4e91acfc1fd23bdf29f36">setNormal</a>(Vector4D&lt; T &gt; const &amp;n)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#afb96324c05f5687b47c66ac8de0db7e2">setNormal</a>(Vector3D&lt; T &gt; const &amp;n)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a12f6e5e54c3bbba5fb63455ab3f735f3">setNormalAndPoint</a>(Vector4D&lt; T &gt; const &amp;n, Point4D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a74d02219965a7c4501daa72af2727eee">setNormalAndPoint</a>(Vector3D&lt; T &gt; const &amp;n, Point3D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a762f5f4ca0e8182a40e257fdab207b77">setPoint</a>(Point4D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a94aadcd32f0ce43507aafd8c74ac7b02">setPoint</a>(Point3D&lt; T &gt; const &amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a6ac54819f460bf94e5be07455b54058f">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a82e7af5642281d56674ecf427a3e5311">~Plane</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">NRE::Math::Plane&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
