<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: NRE::Math::Frustum Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_math_1_1_frustum-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Math::Frustum Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A view frustum used with camera.  
 <a href="class_n_r_e_1_1_math_1_1_frustum.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___frustum_8hpp_source.php">NRE_Frustum.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Math::Frustum:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_math_1_1_frustum.png" alt=""/>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a8b8191a8bfe6f2502871132501ea7338"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a8b8191a8bfe6f2502871132501ea7338">Frustum</a> ()=delete</td></tr>
<tr class="separator:a8b8191a8bfe6f2502871132501ea7338"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeb90c5c37528a7a490776ad957c075eb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#aeb90c5c37528a7a490776ad957c075eb">Frustum</a> (Angle fieldOfView, float r, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D</a>&lt; float &gt; const &amp;d)</td></tr>
<tr class="separator:aeb90c5c37528a7a490776ad957c075eb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4c309ac81ebc2843af0d1a06a9a7ef86"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a4c309ac81ebc2843af0d1a06a9a7ef86">Frustum</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> const &amp;f)=default</td></tr>
<tr class="separator:a4c309ac81ebc2843af0d1a06a9a7ef86"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c5a65f4c47d1e1862cd9698ebd419d5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a0c5a65f4c47d1e1862cd9698ebd419d5">Frustum</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:a0c5a65f4c47d1e1862cd9698ebd419d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e32828fa7c6145022ee29d986d75120"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a7e32828fa7c6145022ee29d986d75120">~Frustum</a> ()=default</td></tr>
<tr class="separator:a7e32828fa7c6145022ee29d986d75120"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a70f0b8991bceffca3152731a42577296"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">Plane</a>&lt; float &gt; const  &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a70f0b8991bceffca3152731a42577296">getPlane</a> (std::size_t index) const</td></tr>
<tr class="separator:a70f0b8991bceffca3152731a42577296"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2f895c6408c8ffce5408d827dc98db81"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a2f895c6408c8ffce5408d827dc98db81">setFov</a> (Angle fieldOfView)</td></tr>
<tr class="separator:a2f895c6408c8ffce5408d827dc98db81"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4d5e50e09cd83a78e23be42de12c4ba5"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a4d5e50e09cd83a78e23be42de12c4ba5">computePlane</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; float &gt; const &amp;eye, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;forward, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;left, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;up)</td></tr>
<tr class="separator:a4d5e50e09cd83a78e23be42de12c4ba5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a74f1ee8b02acd171054e284c0f6e5812"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a74f1ee8b02acd171054e284c0f6e5812">computeProjectionMatrix</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">Matrix4x4</a>&lt; float &gt; &amp;m)</td></tr>
<tr class="separator:a74f1ee8b02acd171054e284c0f6e5812"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab85a19a9bb6c7818e1708f3db30bf7ef"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#ab85a19a9bb6c7818e1708f3db30bf7ef">resize</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D</a>&lt; std::size_t &gt; const &amp;size, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; float &gt; const &amp;eye, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;forward, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;left, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;up)</td></tr>
<tr class="separator:ab85a19a9bb6c7818e1708f3db30bf7ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af7d9047612f776bbc49811f944cfddc7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#af7d9047612f776bbc49811f944cfddc7">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> const &amp;f)=default</td></tr>
<tr class="separator:af7d9047612f776bbc49811f944cfddc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adab0e99fbf0286de9c38980d653b92c6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#adab0e99fbf0286de9c38980d653b92c6">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp;f)=default</td></tr>
<tr class="separator:adab0e99fbf0286de9c38980d653b92c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a661c0844cf4014edabc7bbaed72862c9"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a661c0844cf4014edabc7bbaed72862c9">toString</a> () const</td></tr>
<tr class="separator:a661c0844cf4014edabc7bbaed72862c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A view frustum used with camera. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a8b8191a8bfe6f2502871132501ea7338"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8b8191a8bfe6f2502871132501ea7338">&#9670;&nbsp;</a></span>Frustum() <span class="overload">[1/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Math::Frustum::Frustum </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a id="aeb90c5c37528a7a490776ad957c075eb"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aeb90c5c37528a7a490776ad957c075eb">&#9670;&nbsp;</a></span>Frustum() <span class="overload">[2/4]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Math::Frustum::Frustum </td>
          <td>(</td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>fieldOfView</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>d</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a frustum with his fov, his ratio and the distance vector </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">fieldOfView</td><td>the frustum's fov </td></tr>
    <tr><td class="paramname">r</td><td>the frustum's ratio </td></tr>
    <tr><td class="paramname">d</td><td>the frustum's distance </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a4c309ac81ebc2843af0d1a06a9a7ef86"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4c309ac81ebc2843af0d1a06a9a7ef86">&#9670;&nbsp;</a></span>Frustum() <span class="overload">[3/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Math::Frustum::Frustum </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> const &amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the object to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a0c5a65f4c47d1e1862cd9698ebd419d5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0c5a65f4c47d1e1862cd9698ebd419d5">&#9670;&nbsp;</a></span>Frustum() <span class="overload">[4/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Math::Frustum::Frustum </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the object to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a7e32828fa7c6145022ee29d986d75120"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7e32828fa7c6145022ee29d986d75120">&#9670;&nbsp;</a></span>~Frustum()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Math::Frustum::~Frustum </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php" title="A view frustum used with camera.">Frustum</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a4d5e50e09cd83a78e23be42de12c4ba5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4d5e50e09cd83a78e23be42de12c4ba5">&#9670;&nbsp;</a></span>computePlane()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Math::Frustum::computePlane </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>eye</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>forward</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>left</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>up</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the frustum's planes according to the given vectors </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">eye</td><td>the eye's position </td></tr>
    <tr><td class="paramname">forward</td><td>the forward vector </td></tr>
    <tr><td class="paramname">left</td><td>the left vector </td></tr>
    <tr><td class="paramname">up</td><td>the up vector </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a74f1ee8b02acd171054e284c0f6e5812"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a74f1ee8b02acd171054e284c0f6e5812">&#9670;&nbsp;</a></span>computeProjectionMatrix()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Math::Frustum::computeProjectionMatrix </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php">Matrix4x4</a>&lt; float &gt; &amp;&#160;</td>
          <td class="paramname"><em>m</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Perform a perspective projection on m </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">m</td><td>the matrix to transform </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a70f0b8991bceffca3152731a42577296"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a70f0b8991bceffca3152731a42577296">&#9670;&nbsp;</a></span>getPlane()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_plane.php">Plane</a>&lt;float&gt; const&amp; NRE::Math::Frustum::getPlane </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query a specific plane </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the plane index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding plane </dd></dl>

</div>
</div>
<a id="af7d9047612f776bbc49811f944cfddc7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af7d9047612f776bbc49811f944cfddc7">&#9670;&nbsp;</a></span>operator=() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a>&amp; NRE::Math::Frustum::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> const &amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="adab0e99fbf0286de9c38980d653b92c6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adab0e99fbf0286de9c38980d653b92c6">&#9670;&nbsp;</a></span>operator=() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a>&amp; NRE::Math::Frustum::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php">Frustum</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move f into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="ab85a19a9bb6c7818e1708f3db30bf7ef"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab85a19a9bb6c7818e1708f3db30bf7ef">&#9670;&nbsp;</a></span>resize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Math::Frustum::resize </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php">Vector2D</a>&lt; std::size_t &gt; const &amp;&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>eye</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>forward</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>left</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Vector3D</a>&lt; float &gt; const &amp;&#160;</td>
          <td class="paramname"><em>up</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Resize the frustum according to the given vector </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">size</td><td>the screen's size </td></tr>
    <tr><td class="paramname">eye</td><td>the eye's position </td></tr>
    <tr><td class="paramname">forward</td><td>the forward vector </td></tr>
    <tr><td class="paramname">left</td><td>the left vector </td></tr>
    <tr><td class="paramname">up</td><td>the up vector </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a2f895c6408c8ffce5408d827dc98db81"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2f895c6408c8ffce5408d827dc98db81">&#9670;&nbsp;</a></span>setFov()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Math::Frustum::setFov </td>
          <td>(</td>
          <td class="paramtype">Angle&#160;</td>
          <td class="paramname"><em>fieldOfView</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the frustum field of view </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">fieldOfView</td><td>the new fov </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a661c0844cf4014edabc7bbaed72862c9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a661c0844cf4014edabc7bbaed72862c9">&#9670;&nbsp;</a></span>toString()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String NRE::Math::Frustum::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the frustum into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted frustum </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Frustum/<a class="el" href="_n_r_e___frustum_8hpp_source.php">NRE_Frustum.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
