<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: NRE::Math::Segment4D&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_math_1_1_segment4_d-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Math::Segment4D&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A 4D homogeneous segment.  
 <a href="class_n_r_e_1_1_math_1_1_segment4_d.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___segment4_d_8hpp_source.php">NRE_Segment4D.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Math::Segment4D&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_math_1_1_segment4_d.png" alt=""/>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a8be047aa9307a73551d2dca7026beb8a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a8be047aa9307a73551d2dca7026beb8a">Segment4D</a> ()=default</td></tr>
<tr class="separator:a8be047aa9307a73551d2dca7026beb8a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3bfa48825baefd1ce2c369a1853bf1ca"><td class="memTemplParams" colspan="2">template&lt;class K , class L &gt; </td></tr>
<tr class="memitem:a3bfa48825baefd1ce2c369a1853bf1ca"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a3bfa48825baefd1ce2c369a1853bf1ca">Segment4D</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; K &gt; const &amp;s, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; L &gt; const &amp;e)</td></tr>
<tr class="separator:a3bfa48825baefd1ce2c369a1853bf1ca"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad7d0ddc8282f6822ec05e83ab9d51b02"><td class="memTemplParams" colspan="2">template&lt;class K , class L &gt; </td></tr>
<tr class="memitem:ad7d0ddc8282f6822ec05e83ab9d51b02"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ad7d0ddc8282f6822ec05e83ab9d51b02">Segment4D</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; K &gt; const &amp;s, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; L &gt; const &amp;e)</td></tr>
<tr class="separator:ad7d0ddc8282f6822ec05e83ab9d51b02"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a987a6a04c2051d94cac0935c849ce9b6"><td class="memTemplParams" colspan="2">template&lt;class K , class L , class N , class M , class O , class P &gt; </td></tr>
<tr class="memitem:a987a6a04c2051d94cac0935c849ce9b6"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a987a6a04c2051d94cac0935c849ce9b6">Segment4D</a> (K sX, L sY, N sZ, M eX, O eY, P eZ)</td></tr>
<tr class="separator:a987a6a04c2051d94cac0935c849ce9b6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b8e79fb64caacf6a3b949c30abce268"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a9b8e79fb64caacf6a3b949c30abce268">Segment4D</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> const &amp;s)=default</td></tr>
<tr class="separator:a9b8e79fb64caacf6a3b949c30abce268"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3a43475abae35b1968054eae6d0cd31"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#af3a43475abae35b1968054eae6d0cd31">Segment4D</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> &amp;&amp;s)=default</td></tr>
<tr class="separator:af3a43475abae35b1968054eae6d0cd31"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4b34216691323f07b1b833730605992f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a4b34216691323f07b1b833730605992f">~Segment4D</a> ()=default</td></tr>
<tr class="separator:a4b34216691323f07b1b833730605992f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad5e7e797237e5eb4d4d9bb5e06c9f824"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; T &gt; const  &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ad5e7e797237e5eb4d4d9bb5e06c9f824">getStart</a> () const</td></tr>
<tr class="separator:ad5e7e797237e5eb4d4d9bb5e06c9f824"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b1079202714af2f32b22daf3dd24923"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; T &gt; const  &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a7b1079202714af2f32b22daf3dd24923">getEnd</a> () const</td></tr>
<tr class="separator:a7b1079202714af2f32b22daf3dd24923"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa9d9c85b5c518b06d6ba58b1eef038a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt; T &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aaa9d9c85b5c518b06d6ba58b1eef038a">getVector</a> () const</td></tr>
<tr class="separator:aaa9d9c85b5c518b06d6ba58b1eef038a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a11006b9209c274c86d6cda4bd59f9404"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> const &amp;s)=default</td></tr>
<tr class="separator:a11006b9209c274c86d6cda4bd59f9404"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26de8146a60040499dca07e4057d64f5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a26de8146a60040499dca07e4057d64f5">operator=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> &amp;&amp;s)=default</td></tr>
<tr class="separator:a26de8146a60040499dca07e4057d64f5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a720d442b5503d5640142f78082c6b002"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a720d442b5503d5640142f78082c6b002"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a720d442b5503d5640142f78082c6b002">operator==</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; K &gt; const &amp;s) const</td></tr>
<tr class="separator:a720d442b5503d5640142f78082c6b002"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3cc16c6b435ad5bdeae49572e17b7509"><td class="memTemplParams" colspan="2">template&lt;class K &gt; </td></tr>
<tr class="memitem:a3cc16c6b435ad5bdeae49572e17b7509"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a3cc16c6b435ad5bdeae49572e17b7509">operator !=</a> (<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; K &gt; const &amp;s) const</td></tr>
<tr class="separator:a3cc16c6b435ad5bdeae49572e17b7509"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef6aa7bce89e68ebdec107d72cbd82cd"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aef6aa7bce89e68ebdec107d72cbd82cd">toString</a> () const</td></tr>
<tr class="separator:aef6aa7bce89e68ebdec107d72cbd82cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::Math::Segment4D&lt; T &gt;</h3>

<p>A 4D homogeneous segment. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a8be047aa9307a73551d2dca7026beb8a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8be047aa9307a73551d2dca7026beb8a">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[1/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a id="a3bfa48825baefd1ce2c369a1853bf1ca"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3bfa48825baefd1ce2c369a1853bf1ca">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[2/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt; L &gt; const &amp;&#160;</td>
          <td class="paramname"><em>e</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a segment from his two points </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the segment's start </td></tr>
    <tr><td class="paramname">e</td><td>the segment's end </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="ad7d0ddc8282f6822ec05e83ab9d51b02"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad7d0ddc8282f6822ec05e83ab9d51b02">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[3/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php">Point3D</a>&lt; L &gt; const &amp;&#160;</td>
          <td class="paramname"><em>e</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a segment from his two points </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the segment's start </td></tr>
    <tr><td class="paramname">e</td><td>the segment's end </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a987a6a04c2051d94cac0935c849ce9b6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a987a6a04c2051d94cac0935c849ce9b6">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[4/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K , class L , class N , class M , class O , class P &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramtype">K&#160;</td>
          <td class="paramname"><em>sX</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">L&#160;</td>
          <td class="paramname"><em>sY</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">N&#160;</td>
          <td class="paramname"><em>sZ</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">M&#160;</td>
          <td class="paramname"><em>eX</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">O&#160;</td>
          <td class="paramname"><em>eY</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">P&#160;</td>
          <td class="paramname"><em>eZ</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a segment from his two points </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sX</td><td>the segment's start x </td></tr>
    <tr><td class="paramname">sY</td><td>the segment's start y </td></tr>
    <tr><td class="paramname">sZ</td><td>the segment's start z </td></tr>
    <tr><td class="paramname">eX</td><td>the segment's end x </td></tr>
    <tr><td class="paramname">eY</td><td>the segment's end y </td></tr>
    <tr><td class="paramname">eZ</td><td>the segment's end z </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a9b8e79fb64caacf6a3b949c30abce268"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9b8e79fb64caacf6a3b949c30abce268">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[5/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy s into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the 4D segment to copy the content </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="af3a43475abae35b1968054eae6d0cd31"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af3a43475abae35b1968054eae6d0cd31">&#9670;&nbsp;</a></span>Segment4D() <span class="overload">[6/6]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move s into this, leaving s empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the 4D segment to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a4b34216691323f07b1b833730605992f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4b34216691323f07b1b833730605992f">&#9670;&nbsp;</a></span>~Segment4D()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php" title="A 4D homogeneous segment.">Segment4D</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a7b1079202714af2f32b22daf3dd24923"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7b1079202714af2f32b22daf3dd24923">&#9670;&nbsp;</a></span>getEnd()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt;T&gt; const&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::getEnd </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the end point </dd></dl>

</div>
</div>
<a id="ad5e7e797237e5eb4d4d9bb5e06c9f824"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad5e7e797237e5eb4d4d9bb5e06c9f824">&#9670;&nbsp;</a></span>getStart()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Point4D</a>&lt;T&gt; const&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::getStart </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the start point </dd></dl>

</div>
</div>
<a id="aaa9d9c85b5c518b06d6ba58b1eef038a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aaa9d9c85b5c518b06d6ba58b1eef038a">&#9670;&nbsp;</a></span>getVector()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php">Vector4D</a>&lt;T&gt; <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::getVector </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the segment's vector </dd></dl>

</div>
</div>
<a id="a3cc16c6b435ad5bdeae49572e17b7509"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3cc16c6b435ad5bdeae49572e17b7509">&#9670;&nbsp;</a></span>operator !=()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::operator != </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Difference test between this and s </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the segment to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a id="a11006b9209c274c86d6cda4bd59f9404"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a11006b9209c274c86d6cda4bd59f9404">&#9670;&nbsp;</a></span>operator=() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of s into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the 4D segment to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="a26de8146a60040499dca07e4057d64f5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a26de8146a60040499dca07e4057d64f5">&#9670;&nbsp;</a></span>operator=() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&amp; <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of s into this, leaving s empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the 4D segment to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a id="a720d442b5503d5640142f78082c6b002"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a720d442b5503d5640142f78082c6b002">&#9670;&nbsp;</a></span>operator==()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">Segment4D</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and s </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the segment to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a id="aef6aa7bce89e68ebdec107d72cbd82cd"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aef6aa7bce89e68ebdec107d72cbd82cd">&#9670;&nbsp;</a></span>toString()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">Utility::String <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php">NRE::Math::Segment4D</a>&lt; T &gt;::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the segment into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted segment </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Matrix/4D/<a class="el" href="_n_r_e___matrix4x4_8hpp_source.php">NRE_Matrix4x4.hpp</a></li>
<li>C:/Users/abell/Documents/GitHub/NRE-Math/src/Math/Segment/4D/<a class="el" href="_n_r_e___segment4_d_8hpp_source.php">NRE_Segment4D.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
