<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Math</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">Unit</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Math::Unit&lt; M, L, T, A &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a57dd696d1b37975396c38205a1a64912">getValue</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ad71fa41e004cbebe52bdf8b732315841">operator!=</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a90e5f527460ff2f51fc6fb1d5c6dbde1">operator+</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af70cf71def75fa1c8c6daa7a083ec8e3">operator+=</a>(Unit const &amp;u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a37d034259d9b9a449e853e155300621c">operator-</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a288649a62a1830ea55de2465b382e173">operator-</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af36c98e1e59edd06148aced23fd0b347">operator-=</a>(Unit const &amp;u)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ab0730cc8f070999a8d7e0d9e22acd4f2">operator&lt;</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a6dc17fea4e225bc9e414e630ce70305c">operator&lt;=</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a03ed37f6024fd734b24cce0b9d921012">operator==</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ab566f95c37edbd065288664c37f69366">operator&gt;</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#acce2c22ec4b54ea49dd7e28f1028a3cd">operator&gt;=</a>(Unit const &amp;u) const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a728734518d0ef3c6fbe39e8093d44287">sqrt</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#adc40fb2d7b685adb6e43098da962275d">toString</a>() const</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#acde0194bb69bc8d6bebf8ceb0b142426">Unit</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ad35ea8e9a0c033c4a7dbb5ed85c697d5">Unit</a>(double val)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#aa6f50b4134b5da67ed498f0ef167b602">Unit</a>(long double val)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_math_1_1_unit.php">NRE::Math::Unit&lt; M, L, T, A &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
