<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: File List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content row" id="content">
                        <div class="col-lg-12 panel " style="padding-bottom: 15px;">
                            <div class="panel-body" style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="files.php"><span>File&#160;List</span></a></li>
      <li><a href="globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">File List</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">Here is a list of all documented files with brief descriptions:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span><span onclick="javascript:toggleLevel(5);">5</span><span onclick="javascript:toggleLevel(6);">6</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span id="img_0_" class="iconfopen" onclick="toggleFolder('0_')">&#160;</span><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php" target="_self">src</a></td><td class="desc"></td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_0_" class="arrow" onclick="toggleFolder('0_0_')">&#9660;</span><span id="img_0_0_" class="iconfopen" onclick="toggleFolder('0_0_')">&#160;</span><a class="el" href="dir_0bb4bacb73d7f86c6a963ab22a4f5c20.php" target="_self">Header</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_header_2_n_r_e___math_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_header_2_n_r_e___math_8hpp.php" target="_self">NRE_Math.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Header </td></tr>
<tr id="row_0_1_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_1_" class="arrow" onclick="toggleFolder('0_1_')">&#9660;</span><span id="img_0_1_" class="iconfopen" onclick="toggleFolder('0_1_')">&#160;</span><a class="el" href="dir_3813464283bee2267f39dcf080a84d74.php" target="_self">Math</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_0_" class="arrow" onclick="toggleFolder('0_1_0_')">&#9660;</span><span id="img_0_1_0_" class="iconfopen" onclick="toggleFolder('0_1_0_')">&#160;</span><a class="el" href="dir_732818e93b72bb0dfd477c5bec1e8d99.php" target="_self">Curve</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_0_0_" class="arrow" onclick="toggleFolder('0_1_0_0_')">&#9660;</span><span id="img_0_1_0_0_" class="iconfopen" onclick="toggleFolder('0_1_0_0_')">&#160;</span><a class="el" href="dir_70006416f45ccac6628fade1908531f2.php" target="_self">Bezier</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_1_0_0_0_" class="arrow" onclick="toggleFolder('0_1_0_0_0_')">&#9660;</span><span id="img_0_1_0_0_0_" class="iconfopen" onclick="toggleFolder('0_1_0_0_0_')">&#160;</span><a class="el" href="dir_68c9b736c56a9da6084e0e03ba645a3a.php" target="_self">3D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_0_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___bezier_curve3_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___bezier_curve3_d_8hpp.php" target="_self">NRE_BezierCurve3D.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : BezierCurve3D </td></tr>
<tr id="row_0_1_0_0_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_1_0_0_1_" class="arrow" onclick="toggleFolder('0_1_0_0_1_')">&#9660;</span><span id="img_0_1_0_0_1_" class="iconfopen" onclick="toggleFolder('0_1_0_0_1_')">&#160;</span><a class="el" href="dir_4cb2f31512a0324f40e2ec79e38adf51.php" target="_self">4D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_1_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___bezier_curve4_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___bezier_curve4_d_8hpp.php" target="_self">NRE_BezierCurve4D.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : BezierCurve4D </td></tr>
<tr id="row_0_1_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_1_" class="arrow" onclick="toggleFolder('0_1_1_')">&#9660;</span><span id="img_0_1_1_" class="iconfopen" onclick="toggleFolder('0_1_1_')">&#160;</span><a class="el" href="dir_04356fb591a35ec7606e545595262676.php" target="_self">Frustum</a></td><td class="desc"></td></tr>
<tr id="row_0_1_1_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___frustum_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___frustum_8hpp.php" target="_self">NRE_Frustum.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Frustum </td></tr>
<tr id="row_0_1_2_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_2_" class="arrow" onclick="toggleFolder('0_1_2_')">&#9660;</span><span id="img_0_1_2_" class="iconfopen" onclick="toggleFolder('0_1_2_')">&#160;</span><a class="el" href="dir_e1c0f6ce3cb79c320bb70739a35c37ed.php" target="_self">Matrix</a></td><td class="desc"></td></tr>
<tr id="row_0_1_2_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_2_0_" class="arrow" onclick="toggleFolder('0_1_2_0_')">&#9660;</span><span id="img_0_1_2_0_" class="iconfopen" onclick="toggleFolder('0_1_2_0_')">&#160;</span><a class="el" href="dir_355a5c0f4683da5f546bd2e64b97e777.php" target="_self">3D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_2_0_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___matrix3x3_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___matrix3x3_8hpp.php" target="_self">NRE_Matrix3x3.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Matrix3x3 </td></tr>
<tr id="row_0_1_2_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_2_1_" class="arrow" onclick="toggleFolder('0_1_2_1_')">&#9660;</span><span id="img_0_1_2_1_" class="iconfopen" onclick="toggleFolder('0_1_2_1_')">&#160;</span><a class="el" href="dir_bb685e18c65b7144b4070da0a553f427.php" target="_self">4D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_2_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___matrix4x4_8hpp_source.php"><span class="icondoc"></span></a><b>NRE_Matrix4x4.hpp</b></td><td class="desc"></td></tr>
<tr id="row_0_1_3_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_3_" class="arrow" onclick="toggleFolder('0_1_3_')">&#9660;</span><span id="img_0_1_3_" class="iconfopen" onclick="toggleFolder('0_1_3_')">&#160;</span><a class="el" href="dir_3e10adf8e95f1e65a0c670f6b8e472ad.php" target="_self">Plane</a></td><td class="desc"></td></tr>
<tr id="row_0_1_3_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___plane_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___plane_8hpp.php" target="_self">NRE_Plane.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Plane </td></tr>
<tr id="row_0_1_4_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_4_" class="arrow" onclick="toggleFolder('0_1_4_')">&#9660;</span><span id="img_0_1_4_" class="iconfopen" onclick="toggleFolder('0_1_4_')">&#160;</span><a class="el" href="dir_3bdf3edcab80ec8aaf365e04700bf3c7.php" target="_self">Quaternion</a></td><td class="desc"></td></tr>
<tr id="row_0_1_4_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___quaternion_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___quaternion_8hpp.php" target="_self">NRE_Quaternion.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Quaternion </td></tr>
<tr id="row_0_1_5_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_5_" class="arrow" onclick="toggleFolder('0_1_5_')">&#9660;</span><span id="img_0_1_5_" class="iconfopen" onclick="toggleFolder('0_1_5_')">&#160;</span><a class="el" href="dir_3f75207e03159bed1664f9452b71f96b.php" target="_self">Segment</a></td><td class="desc"></td></tr>
<tr id="row_0_1_5_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_5_0_" class="arrow" onclick="toggleFolder('0_1_5_0_')">&#9660;</span><span id="img_0_1_5_0_" class="iconfopen" onclick="toggleFolder('0_1_5_0_')">&#160;</span><a class="el" href="dir_9c35d3427f50056925f8a9e5449531e6.php" target="_self">3D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_5_0_0_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___segment3_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___segment3_d_8hpp.php" target="_self">NRE_Segment3D.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Segment3D </td></tr>
<tr id="row_0_1_5_1_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_5_1_" class="arrow" onclick="toggleFolder('0_1_5_1_')">&#9660;</span><span id="img_0_1_5_1_" class="iconfopen" onclick="toggleFolder('0_1_5_1_')">&#160;</span><a class="el" href="dir_cd2754b3e59abc673ffa513596c2d487.php" target="_self">4D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_5_1_0_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___segment4_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___segment4_d_8hpp.php" target="_self">NRE_Segment4D.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Segment4D </td></tr>
<tr id="row_0_1_6_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_6_" class="arrow" onclick="toggleFolder('0_1_6_')">&#9660;</span><span id="img_0_1_6_" class="iconfopen" onclick="toggleFolder('0_1_6_')">&#160;</span><a class="el" href="dir_4005e686f12f80d4c04432a698da12f8.php" target="_self">Vector</a></td><td class="desc"></td></tr>
<tr id="row_0_1_6_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_6_0_" class="arrow" onclick="toggleFolder('0_1_6_0_')">&#9660;</span><span id="img_0_1_6_0_" class="iconfopen" onclick="toggleFolder('0_1_6_0_')">&#160;</span><a class="el" href="dir_297243e99995d447ae342dcea0dbde2d.php" target="_self">2D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_6_0_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___vector2_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___vector2_d_8hpp.php" target="_self">NRE_Vector2D.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Vector2D </td></tr>
<tr id="row_0_1_6_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_6_1_" class="arrow" onclick="toggleFolder('0_1_6_1_')">&#9660;</span><span id="img_0_1_6_1_" class="iconfopen" onclick="toggleFolder('0_1_6_1_')">&#160;</span><a class="el" href="dir_3e033f12937dd268a3f1dbce87ebdfd5.php" target="_self">3D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_6_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___vector3_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___vector3_d_8hpp.php" target="_self">NRE_Vector3D.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Vector3D </td></tr>
<tr id="row_0_1_6_2_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_6_2_" class="arrow" onclick="toggleFolder('0_1_6_2_')">&#9660;</span><span id="img_0_1_6_2_" class="iconfopen" onclick="toggleFolder('0_1_6_2_')">&#160;</span><a class="el" href="dir_c8b263e94eb4e39a69f68b819ffff193.php" target="_self">4D</a></td><td class="desc"></td></tr>
<tr id="row_0_1_6_2_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___vector4_d_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___vector4_d_8hpp.php" target="_self">NRE_Vector4D.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's Object : Vector4D </td></tr>
<tr id="row_0_1_7_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_math_2_n_r_e___math_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_math_2_n_r_e___math_8hpp.php" target="_self">NRE_Math.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's function </td></tr>
<tr id="row_0_1_8_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___unit_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___unit_8hpp.php" target="_self">NRE_Unit.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API's unit system </td></tr>
<tr id="row_0_2_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icondoc"></span><a class="el" href="_n_r_e___main_8cpp.php" target="_self">NRE_Main.cpp</a></td><td class="desc">Test of <a class="el" href="namespace_math.php" title="Math&#39;s API. ">Math</a>'s API </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
