<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>scale()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a507ae912f675d3c6a8b88d987ed468fe">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a29a6a76174f4076f0d0a72c552041751">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>Segment3D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a790ef0a4b0b9ccee9c9bcaff894ee2f7">NRE::Math::Segment3D&lt; T &gt;</a>
</li>
<li>Segment4D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ab257836191f2907c9f6d03ff0e77ac71">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>setA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a7edc6bf8ca15f7c94f2c78b642a6d684">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setAngleAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae1c53a59d250b7fb7d62437fa2625073">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a3c1982e7df22f67f2521ac9e7a9fdbe2">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a39a1604b0987d8415611103cc6b84490">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aa5042af0b72fd867e36d077a5741890e">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a82cf3b33e17fcd78d5920aa7235121ad">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a82765763658001fa7228c3e0b808c9ba">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af08ba60087cff64043f49226cef9b3f7">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ad4776b53a54a077f3342ea4e0e2011b3">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad0e31d20afb6950f4fbb359fc1cf1583">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a038810e3aa1a9f14a1c5a45d0c90dac8">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setCoord()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a5969272e8f11b1844dbe051d32855255">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae6aecc3881d571ec59d1674258681434">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a543e584b39dc45b87a1436b35abb0bf7">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setFov()
: <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a2f895c6408c8ffce5408d827dc98db81">NRE::Math::Frustum</a>
</li>
<li>setG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad7794fcc6f53166fc34c0007c3b624e8">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aadd70b2171b76b2b238025de821ef439">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a769505baef52b12436e9ea336ddbdd7d">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setIdentity()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a538aee7efd1c51a801f8f27dfc1efaa7">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af0f9bc0f3592bdeef1b61ca4f08d4939">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a8f39ab8bc99accbb704ff5515c59624e">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a31f0c5b3a695cb3c6f600b9867e15eae">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a22b48fd548fabee8887258603ba22867">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a0e6e969dbf043e2b5f5f63290e5fa634">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a9f2864c4b7c623b637161158ae7f7516">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a4940ace20586c845b96228c2b160a86d">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a752a3264a0d90b4331e7ef8d2ca4880e">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ae94e634f1ea5eb512f8b96f21eba2780">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setNormalAndPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a38bdc9753134a68e0edb8633b061c6c7">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ab03ffb32853e693a81fe0e5eea6ac526">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a297daa2866a290774e6e86c212d34434">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ad0248769e7fb453ed853b3ba654659dd">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setRGB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a453742f910984b8346e5e76dc9c05abd">NRE::Math::Vector3D&lt; T &gt;</a>
</li>
<li>setRGBA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#afea9356e86a055b22aa8c2ab21290bb2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ac18d18ff1fe2c6231b7c9721972fc748">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aac0f84c92e58d56505375a990ba916d0">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ab5b1b01769cefbdd771f3e43c411ecda">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a5ee882af7eeaef4ff3439fdab6614d7a">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#affd206d7637a82777bd2d5317f432068">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a2ccf2960e862f29ecb8f7376446ed549">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#af950b89d24db45f617691300fbb777dd">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a38abf4aeb4499f3f151c961b2ab09c39">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9c3b2a87afe4f292a3516520a205422f">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#adabcceaaaa83104c3d7a1d4dbe2b77e6">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aa0e73f39fe19ae05ed81235839a6468a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a08fdd67f8e0c93134373602a27f63fd2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a05d28d525f52e96129de19ca171a327e">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a629a32e75365614df91197623e68fab6">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a558915236fe79877f742037847beeaa8">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>shearX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a5fa4a6dfb58015ac492fc03e3da2c3ea">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>shearY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a48134c56e97e83e1c80e9e4fbe71eec3">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>sqrt()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a728734518d0ef3c6fbe39e8093d44287">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>squeezeX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a1f9761e4a7afb83a16e64a826f7ae8b4">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>squeezeY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af52978f19a36087045b8db84ea05bb0a">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>stretchX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ab0e2fda083093b94f9fb0d16e50d36d3">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a09980c19cd323514d0dcebc817c374e5">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ab9e27e13e85006301b16f754da5372ad">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae6fb1a3fff8a1748cedd662786dc19b3">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ac8a678347894866de6c443ec7fa7e765">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
