<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_t"></a>- t -</h3><ul>
<li>toString()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a1bc36be181346d58aafad791dee42d0f">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a6de39ef8fa0b8a96955f46f10e963afd">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a661c0844cf4014edabc7bbaed72862c9">NRE::Math::Frustum</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a7cee4fe8ec40f15aac551246b4b3cb94">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a8102264193a2f39aa535a9071f71ebe2">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a148a9dd676341a40ba0b682ce2f539e8">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac8823422d6e88e707e6c3882692f365b">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a576f0a007dbffd7b9a76008ab256309a">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aef6aa7bce89e68ebdec107d72cbd82cd">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#adc40fb2d7b685adb6e43098da962275d">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aac4f065905420acf119e79b020d61c5c">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae846d577e041459b663c646a90ed65d8">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a9a60b47199873f76c28f7e124585f944">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>translate()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ae1cd2fa45f97f8906598dff75d156aab">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a88a90fa205372aed9c72375800ed273c">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>transpose()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a81bcd3c4f3bd75ce1fc34ef658ece0a4">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a2cd2e06d94d0e11a4732a60f3a381cc2">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
