<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li class="current"><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>operator!=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a1cc3102ce038ea248ff2564d4ee4ec03">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a702f726937593f46c12df1c4d982aa59">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a58a5d713ef0706697e553d02e762b5d9">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a3ad55959306d5f542bf85711e38f8fb6">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ac975058a41f3444a1ce1c208bf92678f">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#aa7c1f86cd9a1c6a6d02c6ed251f56d08">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a929995805e833908e181621827b75c20">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad6c75e15563e5cd992b3a9406d4fa6b5">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ae9b98b68b70196b9cd4a960b189e467d">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator*()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a37b01afaba72105eee53e046ab639edb">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae02d244fed1b867dd142e3717658b0ee">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a3cc218b9d5c28670b311bbb319944003">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a162d1d97d7bfc9343bc07e67f6741d38">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ab102e0a6a0d552574279119760db33ab">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a01186fcdb8cf4844f33146c3a0dffede">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator*=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ae9978571d49dca5a6bbef40593a4a36b">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a567720c6d0e0b84613457ed3aee9bbe3">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a07bca41dad96c32b91199458f35ff904">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ab5e9835a77a1f60f5e5a716e3f5a23d6">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad8faff680f6010a67838180950bd26f5">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a56fb4c8af529125325e6a82958656d74">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator+()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aed3be27b2e227cbff93859d3ee0809e7">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ab06ecca34df1008a881ca97dfc965ea4">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a571c89a1d60706d1a5d7923feecf5a39">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a51dc628c8d4cc6c3a691c06ae4516ffc">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a6282478ecb461ccd05b98900f2c76ffa">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a4df04d05e17e2591f4a9ec729e26955d">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator+=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a86227fbfbc2634525131eb016d556388">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a46482970d304c82ef1c4f5dbaa636b0b">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af70cf71def75fa1c8c6daa7a083ec8e3">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a1f3a3cf45ff2f991502b0706b3232884">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad2bff1625040ae3105d0968b8d181bd0">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a7ab75d29c8d1e4098775506f202927f2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator-()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#afacbe74f8f037e4453a1fd7ef7dfdc38">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af0e73ff0c4ef8f7aa7523cebfae938f2">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ad395b12f20018095c4ddba74531a4f22">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a89474b04508c997c176b04eb1ac601e7">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a1e957d094dc6da79942ae6d7e222d621">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a05670ea5460586f79e78a975a62c1aa1">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator-=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af7d3a39809b9e3b1bf76efec70117b11">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a90c0baa70df3c583b72e4d29d548b610">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af36c98e1e59edd06148aced23fd0b347">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#afbba221c25eb11fb5027e66f979fa123">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae640ab6b67d1c70bf382c25671a429dc">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8bad8d4a316ed1a0dbec743e64d10b43">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator/()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a09808eceeecccd5b43a069cd95d82edb">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a6f9a117add80b60edb462124a651ac64">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aeff9792455557a08a8e06ee27f12b2a6">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0fbab2f624a9bebbf1f3be8decac60b6">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a2482a8c27534f64ad0540f75fc3b0643">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator/=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a3ed2aad0aa854c45e3b586d59a6f8dfc">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a156d8d63a8060ab56f489815dec7f303">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a6b2bb083dc0763bc569d0eb036f0d342">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a48e38960a7b58d7b20f0a641154fe64d">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a134506c1e1292dbaa6a1fa393834add9">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&lt;()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a57861b23767a77366a10f56c28afb081">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a582f3ca0edbf4c4dfc849a195bbc9f4c">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#acacbb2d3525cb056a165caf8fd8557bc">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#af18ea3f5c0f6b3c381df0a0fe6a53d44">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&lt;=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ad7d0a14ab68567e3b917d783df57d4bc">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a9d2b221576594341ee28a92e0b95075e">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aef24dc94f6df4b408a486a95cb49df28">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a1309184351736a61fdaf03cb1eb3f0c6">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a4dac44314e1e432b221b1b3b11b2d825">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#af7d9047612f776bbc49811f944cfddc7">NRE::Math::Frustum</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ae1c763215f22622bd6a86aea3e572639">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af0af920b2e9bb4da3b3ccf359d7f1f5a">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aff4e35b9d557e9be76a2704d3b4a62c9">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a78d3fafa8fb5345c20e6540bfa4835b7">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a267b1ac46799e64fe7ec326ff994457c">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a59bf5d70ea419a833ef9b015839c6a12">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0780e79c4ab9f2ad2f3e24871d8b64f6">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a03f9efec7ea3dda163209b2a7c7ddc9e">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator==()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a6572ff63d1e9e87570a28511cbd798e3">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a549092d235a6eac0eeeb7088f169b177">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a8d53debe9351959bc35c52a1e91702be">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#abbdb718a0712a5380802098fc5dd5adf">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a57d43b2e38e9d8226e7ed12bf22922ab">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a3e285181e6cbf15a0c03235062bfb3a0">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aeda0d7e21899843c330e2afcd5aa33cf">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aa018c02726a546b8c22c0a1846343dfc">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a7ae1f0b844fdb53022eefb130f19792a">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&gt;()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a57b0e40e80ebccbe92dec4ddcc688b30">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a6074b2610a91e5d2f3f2aa04a81e3ec1">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a74aab1ffb524b25fd50d4453a980fd01">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a713cd8de52e04b8f693524dad8fb9423">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&gt;=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a5cc535353c6a7c0f7b741eddb1eb1328">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aad6cde4e03ee595d5a7ed6598f2e0455">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a436716968f11ef7b01ae1c0bd366288d">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#adf2fa9eb4602891047820e6778b0da62">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator[]()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a74a49c78163f2125ea4aa6cd73a87f30">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#aa1c7c91ef3273975336944d8647a808f">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af8e87a95bcb468bf1ac8cf03b8f0441f">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa6c37d2ee0f7eb742caeb9f262b6e661">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a0331309613d64d9e0416e1df4f5e9d8b">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aa1e58490aff75f2928a7d7fde46f53f5">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a1f0089aa9cc5a1ddd796e27afaac363a">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator^()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a1f6fac7d478be83c31acaed8bfbb266e">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a364a0f30ceb8eafd4a4cd7201cf80926">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator^=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a58b84fcb4f3e4a67de2141fef79e8723">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ad43f5428f9cc3e9288517887d1349529">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator|()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a49782388779e818544927c9fc8303ee8">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a84f52f3e79b893f079c1ca624901602c">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a344de60ed8d3c2eb3d2f08781145f35e">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator|=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a7a8072d380c49d8fd13ce5b75cd587d3">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a3f5fd4dab9fdc169c4057c1ac7a41059">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a3f9834b3542e8267be161165c87c4a9e">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>ortho()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1a7c6f74cd63544d038f44ad22712167">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>ortho2D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a93f26c985a856ed149930334322e7fec">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
