<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>scale()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a7363f7794956d19ee69cce2c2e537a80">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad6454c713aa2ab0f258b2486b7342765">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>Segment3D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a72df4059682b397b84ac499569a1895b">NRE::Math::Segment3D&lt; T &gt;</a>
</li>
<li>Segment4D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ae5a23c680fbf4dd82c3a007264e23608">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>setA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8fa14964830b9692edcda6e8f90e0173">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setAngleAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae1c53a59d250b7fb7d62437fa2625073">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a73c4e134df19d879347b655a0a271c82">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a76ec4eab396b5ee7d4a4dbe44cc9b0cc">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a43c656891d269558a279c0839e43d1fe">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a005f3a836279f92372ac7179f5e6b0a1">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#afdd7c49ecc9d5b5def3f3af5c8cffa13">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afe3cec10fc0c4714765203e38f798a54">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ae2287876bca531e8c65bb4544fb82149">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af07c425da2528f624e0437347ff8d5fc">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad790830fcb3da5892229975f0cb8b0c1">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setCoord()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#acae2dba8997626d0f54407d1c7bc79f2">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad047951c6b0dd5fafaeb002d12572187">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#adca379685f7e5c5dca8896ed4297b8ea">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setFov()
: <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a2f895c6408c8ffce5408d827dc98db81">NRE::Math::Frustum</a>
</li>
<li>setG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a559830e269cf5f86440bf964d8fa7646">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a15b2d9117d59f4629811024f1aa4edc9">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a13dd252d891b09a377bf8803c35f4cb1">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setIdentity()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a7bac4af98c7f240f94cc343995615c86">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a88feb2b6536114614fa18b8169318e1d">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa2fe3982d5a5f0c86513c8bd6cf0158c">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a2bd19f2e0c68964df59cbe9922420d80">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a22242cd4d4ed933b84e2a33c6e457c84">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a2e32090e84ebf5675cba3ef7601bb3bf">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1c5df74c01f1622674a64dff4b674c3a">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#acb9d9167bfe1b1cba830bf74b9c14d0b">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7ef6b7cc41ace5574268e1b015fc20da">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abf9c3d33b08e19803e3b9649c75aa8b1">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ac9d2733e98125eed3250bfa94bea8208">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setNormalAndPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a834bd4f96aa5f294dc53769897f86faf">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a1a1399fdd0b69e00cd99e060827c84e8">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#af44751ca7404fc3bd378399d6099dc02">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a45d2afcd9c75e1806bc246281b44b0fd">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setRGB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a10b1cab637eb39d3155a3a3f2a44fb0a">NRE::Math::Vector3D&lt; T &gt;</a>
</li>
<li>setRGBA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a6b0315651d50d0ef35551109e9a31e84">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a8fbd52013cb716f9f3db5b705c746220">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa558dd0fc08159836151b498ea670812">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#acbb877be71ee64451f25590bf0291870">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ae7ec81b403156543fb7d032b93dae33c">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9b69e61734bcb338d4f30e9332927c7f">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ace6ab9e4c0fd771160bf628f376b1db2">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a868798c0d24687e868f6d1e8aa220b1d">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a04d5947c75d8c91dcfb7493e0ed765e4">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aea09f7397244457d1ac93b544752af74">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a894ce62ab59938f6fea66277cd0f589a">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae0ee7c58b164322c8010065492ec724d">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#afa8108fcdbead7828f99cc1a3ec669cb">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2cb08d334a509dee9f157604fc8cc552">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a187cfdc11d6e54b2b6cdd5befbe60b4a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a79da0238087ae58ea06a7b7ec6415533">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>shearX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a0e5e3461c806fe7f9cd05408d2997477">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>shearY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af52d12ba3414cb354fdda81e3a63973a">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>sqrt()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a728734518d0ef3c6fbe39e8093d44287">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>squeezeX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a637e7e0087b2ad5fba29d9930e65424c">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>squeezeY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aff9916e2e922d75bb30b1fce99b55afa">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>stretchX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a75c5e854386f76aa08008e5feb79bd69">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a08213b41f6400a5b0cb359c7eff6a9ba">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ac412fcf74d01e03e6fc763bb7daf6bb6">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a987a6a24b69a6ed672faf2a3038653b3">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae2494a3bc36e5612663939e32a74e5a6">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
