<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li class="current"><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8d3a67b94eb0691b684e94790420bff2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a783b070c5b47509f79d6b035a7b09c64">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a5feca9230bad1d8a8004abcb161e9ac9">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a53dae7f469a135fb0fb1776e86fa4651">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aa2a9086e29d23a64dc30542b7d487bfe">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a551309ea07648d8d0a52f9e0061e11cd">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a9319e13b7b2406aaa25edefb289b76d2">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afaadd0584eebcd6713e299d8819596a0">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a24202580d3ce17d5a93236e36a41cdfc">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a3d9902378a2bc0e10b2df0c07f75c2fa">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad4624e1695e2161c1a008676ed5761db">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getDeterminant()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a260fe35c48abfd0fe3fa6ac21055a525">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abab64fd97e3718ec6b6c3153eae7e0f7">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getEnd()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#aae3c02691ab2824eb7a3b6e1b0d5d360">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aa78f30fedb913b7e4dca0af67501e445">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae2b0e961bc8147c9a12f415c9efbcb94">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a77a1ec531d6fe24d65640a316078f1b0">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a43e9ed15954cf730cf3154ffec09bb61">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>getL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a59ba6113104d98b9c2867f5e86d38466">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af18ca0ca5d8985baca129fa2a5fc7bb8">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#abec135bee62f5595be949fe36f7c2bb8">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a038a1b37794b229c2fbef8be54d25f37">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a659b949b86cfa857961a8e0a20e04571">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa8408fda644b045a014768b54ca10789">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1d6b181af872ec7c4199869cc0ced5bf">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aedde72678d5e2d8f2ae5d1ae184387c9">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getPlane()
: <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#af64005dd435f7874b287c2bb10e966e9">NRE::Math::Frustum</a>
</li>
<li>getPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ad76aba00eb1f424e1776737edaab4f69">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#af8ace4b3107b7a451b393f7cd096d64a">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a46276cd4adb703a1d2660dd3749da009">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getQuaternion()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#abd50e6dd1ef2d925315f3afcee49a522">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ab47f9b48d3b91afd6bb0b481dc54f36b">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#af3fb5cc4b82563473058af94ed3b18dc">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a6a979821dcf6d858a1e4d751f7a42896">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ae5fcb54b717ecb456024df099a36f6f6">NRE::Math::BezierCurve4D</a>
</li>
<li>getStart()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a76dcdeb58b1bbeea5e5fe66b6bdde7eb">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ab13a15ea5c8a5a7fddfdb0ce04242dc8">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getValue()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a8ef43f0978c973892ec6ee475ebd1d8d">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>getVector()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a66e0b0add734906372bea1c5ba4a8ede">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a113b9f61a59d80e1a894dc066018e53e">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a87a2232db745e265d1de7b1f45ae94c3">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a461b9839c89b36b8b1d3339dca283f7e">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a99cc1364656712439886f1cb732ef352">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#af3d0e9795e471774a806dbb4db5030c4">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a3a2394b397491fcd9493a1108f30109c">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a6f38989cfecc5987fdda4126ecdc17e2">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#af9a91fc8105a8ca449270747273f5b79">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a8b74222b0ad9f00b28177ac51d2931d6">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#acab4df35acef9a21408882db7b0dea7a">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aff90194d75579e485e2dd4d66106f506">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ac1d735d9c7ddbe26a0f12625a17acfde">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a93767c013073a0ee821c0690b3c08edf">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0fe3d36bfc1fc6a84d5d1d54d94ba291">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a6d05d7242e635d6d30f65349a64653a0">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
