<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>scale()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a1bb1b384cb9c9dafd1c34c2760e90cf9">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ac1efdc356918041afe7a0878a479d03c">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>Segment3D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#aa09292b8a2b4a23cca1b9fc65579a371">NRE::Math::Segment3D&lt; T &gt;</a>
</li>
<li>Segment4D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ab257836191f2907c9f6d03ff0e77ac71">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>setA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aa1b6d2f9aa11119e6fea4dddb8e33f10">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setAngleAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a23d8d5c15694d3df5560295434c9fa96">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a98acf0239098af362030231af07d2233">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aa856e08544d51bd9a4e7d754831d44c1">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a5fc54ef3c5ffd9bda8d717d2e79f4eee">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a4753c382eec65241782ff4bd9384a0ec">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a7ec136103fbe4d7abf7b5b13767474a3">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a4bdd7a60ec041125089d62ba80be6da8">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a988e8447c34276d7e113d8e1433121b0">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae436576b497cbd252963421534a85869">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a5ae80495052be13b9d524e0a0657fda0">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setCoord()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aba65c776cbd77609e630e591f4b75dda">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#adbc1b8563e9ba3be58137c5e22decf4c">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a36296018a13136ffbdb75c15b1c9fd4d">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a8592b6949e549182225b77537ca7ec01">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a811765e6e18cb9f8ad351ac263564ec0">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a19b429efbc0a94da22c141505a04bd73">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setIdentity()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a538aee7efd1c51a801f8f27dfc1efaa7">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#af0f9bc0f3592bdeef1b61ca4f08d4939">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a06ead9af6d624c1572b219a5a1825ce7">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>setL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a9f019f44fa68e5a3892f291737a6de22">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa430ab1ecf9fe59e5b92034eb95e0d0a">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a194a3791997feada702a0a864e72ebd7">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a71376172f60e55fe6d64a63775fde4c3">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af6e3a99e9b955b5a4103e9dc2076fa18">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a5486f85f0f8326a56b163af8c35da711">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#afbd80da2f4bcbdc8725dec1a068f4d11">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>setNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a5d8b503157d4e91acfc1fd23bdf29f36">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setNormalAndPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a74d02219965a7c4501daa72af2727eee">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a762f5f4ca0e8182a40e257fdab207b77">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>setR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0ed80cef6bf71e930ccb8595efeacd06">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a9201dadb2a32e9a160051116ab90532e">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setRGB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a00a93aca6cbdf5fb61b4241cdcab0430">NRE::Math::Vector3D&lt; T &gt;</a>
</li>
<li>setRGBA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8c5732120815b499b2326b7da08d1462">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ace552af23a155b35e862734e9f9d2ff2">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>setW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aaa64ad7e7e8402b450ec601f87e40665">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aa6491caa7cfc69a73bb08d570bb8741d">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a275bfa8f5859f968d3ce21e825920dde">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a94d23755f70656859a0fa8512f90079c">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a622a92d8d0b1f46c2e882e562141f867">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a136c965574ccd7935ec242fc3b2c2eb3">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a515b0404b9ae1279dc7a05cd88461d12">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a4cf7a35dcd77f6ceb53af34b344aa826">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a9296849f27aea4b9c352f078b8916bfc">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a4179f983661e5f2b0faed5b0ceed2faf">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a17fd368a3f25bdc34b7a4d3ce491cc18">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>setZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a4037191f26b8fe6afc3245b06caebe6b">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad75903852c7056bfcc5e20b8cfef9188">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ab1ee9233d4bcf501a3fb612b1ee4003c">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>shearX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#adeeeb8d234130dc0c151e7752bc70201">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>shearY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a2aa7833e89f07c8159f19c0d17f23bec">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>sqrt()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a728734518d0ef3c6fbe39e8093d44287">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>squeezeX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a5e02514031d20318b9e780c138e5ad49">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>squeezeY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a1c6d77b5dba9026b37d79a9815315f4c">NRE::Math::Matrix3x3&lt; T &gt;</a>
</li>
<li>stretchX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a676df196a6297df4e016df5fc9c80102">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abeeff06e26a21b1e8c84828df9a842fa">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#af2f63863d5db5b50d5f3b699ccd2aafb">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7fe55e1f7493a615c88f648a446b23c5">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>stretchZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1bd9dcd74f297324f10ef7de3e3a4668">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
