<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li class="current"><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a47edb62f6f7737ea6fe29fb3f8fcc4ce">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a69cdacf9fabe116ef083ab918ac2865a">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aceec4723c7610a82a27959c8f09b73bd">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a46c97d93161cef378eea58c9c73c13d1">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aac14b2b94fb67f4977664cb399a1f468">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a1cb128ee22daf5beb309a39e7b4567c5">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ac36f48d23575a8b85c028168876cee0c">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a4ae9063b43447d41df0d5a0f8cf31bb8">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a0722ab55923c11e84bf55c91242c4274">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a6512a118a004086fba41c608b4a127ef">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a969b2881efba44b1aa4f70f47dca3a2a">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getDeterminant()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ad6b3520c5fde6e77f6025447cfcc50d4">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#abc91cba6cfeccacbec42d82ce740ff19">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getEnd()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#ae89b9f841d5ca4e8500c0e7f9016de44">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a9aca09099bcb5c10993c1029e7a46daf">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#afb49b844ee4c24241f8c6972c3fec140">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a74d815a335ef97675611abe187dbfaee">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#aa376263f8b1391c5fd9b80e0f2275cf6">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>getL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a4e0e0edd9969a970464e4098baca29ae">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a03be74447a2fe0c66af68b9cde906e0e">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a389a7425497eca58b3e94ba8f88d6e3a">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a17c6b3570458e4c281d86f3764783a2c">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a66fda6eb7da6ec88fd5eea1a850db1bf">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a135d1b56144f7abb6a45701ed19a800c">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7da33dbf892ef7d4b5c3861426124ff9">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ad32174f103787ce5012844ea677e8c31">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ad76aba00eb1f424e1776737edaab4f69">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#af8ace4b3107b7a451b393f7cd096d64a">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#ab4ce67f0384ee4763f6a922dc6deb647">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getQuaternion()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a51183223d4b9c7955bbe03d0147b48ff">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ab4f2744382427f483dc9716cfa12bbfc">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a71da5c8cdb5acf98d02ce53de4050ac3">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a6a979821dcf6d858a1e4d751f7a42896">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ae5fcb54b717ecb456024df099a36f6f6">NRE::Math::BezierCurve4D</a>
</li>
<li>getStart()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#ad83cfc126456eeb8593e4a98d914039b">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aef8e419bc9a678688ca5f6aff74f76e4">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getValue()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a8ef43f0978c973892ec6ee475ebd1d8d">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>getVector()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a60a87a35cebed3faf2481b17573797e2">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a38964e722e6ba6fd14fe95233cbd359e">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac1e7605f337578de78e84c7087480f4a">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a6f1609d3220a8348a7023e63bb5a90f9">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aa62b86864e11f02da092c781f60b62a5">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aa0717eaee838e8a29dc6171a7adf2b73">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a4516b1f558aa724a6cc8f0352abeef3f">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aa208efa6ace10aa41c7e05165ecef8e7">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a4479b29c1625b952fdce3611dd3266c7">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a2e025252dbd1aae5b9e610e856c745c2">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a4bcd055e32b0084addf627d693a2bfb1">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0653a5cdbbde436f51bf293f63965d2a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ac61e8291f4b62605f507a24254b3b79f">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ad19616cc2549941bac2569549d379131">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a1d3d9ffe38e46ad28d3bcb5a9f6f8e18">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8decd1bc00420a11c692f2bc96e51333">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
