<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a id="index_g"></a>- g -</h3><ul>
<li>getA()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a01ff0bce20c2665c6b76a9a6d22e47ec">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getAxis()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a0c31f1d471ce1a853e4c3e9eeb818a7e">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getB()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ab0d39a7da541473b7df23c72834b4d64">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a35ed772b63afcdf195655692ec8b4b22">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getC1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ae1e1d419b4470dc9cc53c97272bcd8bc">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aaa694d24386e834ea55fe2594e50fb72">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a7e4ad2399fd35b5253ab045906e2f807">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a60d59cce52c509043e2e50396fadfb2c">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a1a8311bc060b977ee2b20df734ff7d0b">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ace9a9626827901d6ebddca1507c1430e">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getC4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a6ff2a586df5a95610ccdcd47e740108a">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getDeterminant()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#abb112c0b85de6a5140a507f901b1f70d">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ab43c82ae7fdc333def288ed56bef7673">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getEnd()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#ad887abfd637eb61eb0db34844dde4a71">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a7b1079202714af2f32b22daf3dd24923">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getG()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a5f5c39a52b35d32066041b61e18f8e6a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a7c780170343220e60d8865998351e706">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getH()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a431744856eb2b6798369e1eb7b2a9715">NRE::Math::Vector2D&lt; T &gt;</a>
</li>
<li>getL1()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a8787c70fe4bc88ea3c724dfd4371a9fd">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#adcf11fc73ebc9b5ab68e4356bd7e2d9b">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL2()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ad7f211677d07fd729e43a49f0642ad6e">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a359b3de8375fc61f93aada1bf890fc5b">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL3()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a58a7ba22229135116e93c16f6dffe56b">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad01f05210006836e5d6a4d5316f691e0">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getL4()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7badc60f7e2c0dbf6fd044ea145069d7">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>getNormal()
: <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a60bfac3f071cbdb103c28d6f6bb29e25">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getPlane()
: <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#a70f0b8991bceffca3152731a42577296">NRE::Math::Frustum</a>
</li>
<li>getPoint()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#afd89fa3c2448a334c6cda56e044bf932">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ab3f98702f37d9a46a9b9c1bc47dfcf06">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a1cd57c4cb9fe2f9564d1970df1628a8d">NRE::Math::Plane&lt; T &gt;</a>
</li>
<li>getQuaternion()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#aeccb2a1b8464b0815546ce4fb0bf58a4">NRE::Math::Quaternion&lt; T &gt;</a>
</li>
<li>getR()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a486a77fbccaddfdfc0c43c838fe5e164">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a2ba7243457f25f7e9742093edeeca695">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getSize()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a8c90a8e4e0f3da2823118c9a7095f2ec">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#ac60fa3c1501c7f4b584f0d494f6d1281">NRE::Math::BezierCurve4D</a>
</li>
<li>getStart()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#ac7eecba268a01aa537501c681e2c7f2d">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#ad5e7e797237e5eb4d4d9bb5e06c9f824">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getValue()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a57dd696d1b37975396c38205a1a64912">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>getVector()
: <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#adcbbd4f8150276dbc1fcbede067d577b">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#aaa9d9c85b5c518b06d6ba58b1eef038a">NRE::Math::Segment4D&lt; T &gt;</a>
</li>
<li>getW()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac2a8ede83e9fdee10a3b90f73d78be78">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a67afe02f4b0dceaf1ef2f708d3459d5f">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#afcec8a1b0453cde4c068f102c1e80d2f">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getX()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac3fd3244b84988582c52737d5657685a">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a61896a30a0012d4dda16dee15e78a1d0">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad8ec77160a61f09cd472e9892bb8a461">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aace3c6ab1d99767fbc951a1738f1d5a2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getY()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a68dbcdfac818a38e44646633c83978db">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a2a9d3b53dcd9c891a2ce462ff0f79770">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a7936f35369ccbe0d2da0d51edd2bd87a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#af7c45abea7da6822542849e1279f4709">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>getZ()
: <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a22494c74ff791a1d62dd19e2d822435c">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#acfb56cc119b7682b7bb4eda9b24b015c">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#af81f1f0403ba6855a9df334e9cc178b4">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
