<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.15"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.15 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_o"></a>- o -</h3><ul>
<li>operator !=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a463bdfae3cec53ab4a1168ab3281c513">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ab35f96a50e3d7444f5675e08c8206d56">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a2264a6c449a20365b05e48bf59533fbd">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#aabe24152b0875213ee566aec7731ccad">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a3cc16c6b435ad5bdeae49572e17b7509">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a1eed1f3bde6f3657549d7bbf3cda2854">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a99652545f84dd633760f7bfad9dbe0e1">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a088f329f841954d5d30fca8d0db2799d">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator *()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ad9308fe800280ee11f4a79baba0e9400">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7cb4c95987658f0918369dadb0a55647">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#a9d7b703ea6c6d7a8e6f2bcc949f54774">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#abf2949669220e723edf84198ae032acc">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0f8b28b8dbb534ab87e22a1f9eb9a435">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aebc60360c51b82de0096206a11b9e7a2">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator *=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#aa2f2101194c5fc449484350a2db078af">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a7ce12e8c0c8b55de76529b0aca6d9e24">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ae75df23bed763e5d87dcb80d1b6cb1b8">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a5f4095d0a3a3048e89539448d3f13f01">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aae5dd4de35123a54cd256d3a4e58ec26">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aadd542d784fce3b97ca0516ff485805c">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator -()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a9a3c59b1f39dfbacc56dc6c605377e77">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa562f926ae35c73fee199d4ab0f163be">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a30bd2f48694969d9795223ff75fa411a">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a9a8199aec3fc6dfff07b8c1a0d7665f8">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ae13f582fc435822d6c229d6574174eba">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator -=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a4fc3ebfa87bdbccffb6284b1c33a1555">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ae69e1f8e72f2c1eaf35c04a4e6d2d05c">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a60079a1c5c3264f39db744bf0ef6e4b5">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a61d0d4b6e93ce40f970fdc01e6a53a78">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ac6fa506a462f9088461d3d6dc1b3b708">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator &gt;()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a4d5c377685b942c669c1988ffff4aae2">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#af79cb144722829481932a6656f765dfd">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a8f2c7cad206f60ae14e80876d968e9ed">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator &gt;=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a1951ea9da1f75bb58712dba335c1e84d">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a57640b9acbb12b0c99c3e3d41bd090f0">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#afc447db337b73dddb88e98ca932c8667">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator []()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#ad5650e22699bb679f27f87388a9c3a7b">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a12f9875f93a1f9ce6aea62cad3734d2b">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#acf1f99d9952a2bf9eaefec9f93325c68">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a16b0183346240a89ba4e592b125f38bc">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a026b4e8d3ba98577886e41cf3674a83a">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#acad74f79ace1f2ecff80083b3ed36114">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a71daa46a1a52fb090aab5d0a1af951fd">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator ^()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a42e1ee939c99950245e8de3bd5205133">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a03e6cc24af34fbf71ac4c3864ae95037">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator ^=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a2e0f7327bd0723722524f43b81d78b01">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a3d925a3d85c8a11e5e360dfb99d42b37">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator!=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ad71fa41e004cbebe52bdf8b732315841">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>operator()()
: <a class="el" href="classstd_1_1hash_3_01_n_r_e_1_1_math_1_1_vector3_d_3_01float_01_4_01_4.php#a762cf4b4c55f2a77f8cfc379858debed">std::hash&lt; NRE::Math::Vector3D&lt; float &gt; &gt;</a>
</li>
<li>operator+()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a5aacaa18227665488887d69b89d66d92">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#ad12ee8be392d64ba75203ad02e0d492d">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a90e5f527460ff2f51fc6fb1d5c6dbde1">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a6e6c49e71e7acb72b0b8413d05924eab">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#adaed270c421c564b0206cb3a5b6cb9de">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a460f3a646a44e0dd129280eff215bef8">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator+=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a163e1da1b3c1c6355732354aaa2c2557">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a8516b2aed9f7d6dae67c43e7d24ac5d1">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af70cf71def75fa1c8c6daa7a083ec8e3">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#acac64d98f1d95bd16e5ed5ae02754283">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a0afa8627aec15b8e5b033844cdd1f8f7">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#aa40fc443bf77598f83faac93ba11929f">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator-()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a37d034259d9b9a449e853e155300621c">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>operator-=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#af36c98e1e59edd06148aced23fd0b347">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>operator/()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a26aaed7904015e73caab2611b40ad795">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a2eba5de1b53025d1497139a9bef93379">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a5e808cb8e5f17b19e3920eec6e36ea3c">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a18ec3b7a48b4c8510046e13ded340abf">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ac882f95d2a010366bae0a15c85e57515">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator/=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ad54ae5ee1225741d549a2d53194fae19">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a034e86255879fe628ea5bdad06f3e1f6">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#abdfbe163dee1d5fe2dffc25d7b6ed40d">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ad61078296a8d9c9fd6030dd8f33c3a70">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a52865a646111eaf68e9771a9b84149ce">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&lt;()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ab0730cc8f070999a8d7e0d9e22acd4f2">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a4636215ba01fc6796533331a21e08c1b">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a926e9852e04e17eb252bc9a87f8f7d9d">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ae4ec289b2d1189b313486a9f3c2a7957">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&lt;=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a6dc17fea4e225bc9e414e630ce70305c">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#afd17be72091a5669c96aca3e24d14f5b">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a9dc4f1b0bffb27d6ff9885bec420743a">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ae0de1f140819e7ba48190f21c8cf7d08">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve3_d.php#a2b04688e57f83fb55ed0cba0adbbcc0e">NRE::Math::BezierCurve3D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_bezier_curve4_d.php#a5d40d8cd0a22a3dec6153b16fcff37b2">NRE::Math::BezierCurve4D</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_frustum.php#adab0e99fbf0286de9c38980d653b92c6">NRE::Math::Frustum</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#a005a48d111211d78692a252d5b08a9fe">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa259baf3544be31b09d0996cb42f037a">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#aff4e35b9d557e9be76a2704d3b4a62c9">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_quaternion.php#ac567afb3fb86f4233db1078d8f955dc8">NRE::Math::Quaternion&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a267b1ac46799e64fe7ec326ff994457c">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a11006b9209c274c86d6cda4bd59f9404">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#ab560b6c8821adedfb37968074e530f21">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a1574890cdcfa7f6651732fb3aa5667f7">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a05921d8cf0d6ab79100e9ba7ca351feb">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator==()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix3x3.php#ac471a0d527b35b2b1c28c18acbdf0691">NRE::Math::Matrix3x3&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#aa2c1684f4ce7457c8df7209ca96646fa">NRE::Math::Matrix4x4&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_plane.php#a7cb617761f2993f099d8d10137570d46">NRE::Math::Plane&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment3_d.php#a4ee39c24fee561ca49af0993d7a0880b">NRE::Math::Segment3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_segment4_d.php#a720d442b5503d5640142f78082c6b002">NRE::Math::Segment4D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#a03ed37f6024fd734b24cce0b9d921012">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a2348adf636168e4eb09562f2b9cb658e">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#a19c58fae4ff01c1914e8f29c1105301c">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a5e7d2794212483efaf5163f491711e4a">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator&gt;()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#ab566f95c37edbd065288664c37f69366">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>operator&gt;=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_unit.php#acce2c22ec4b54ea49dd7e28f1028a3cd">NRE::Math::Unit&lt; M, L, T, A &gt;</a>
</li>
<li>operator|()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a9e95a7ac6f8a5ee3492fef7f3515a014">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#ae8818993ef6604ae4c9793fb71e5789f">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#a54ed86b07ede49f2e46f17254c965d2f">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>operator|=()
: <a class="el" href="class_n_r_e_1_1_math_1_1_vector2_d.php#a4b9cb23d1d592506dca6065ece2a141a">NRE::Math::Vector2D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector3_d.php#aa8dd2164dd93dc753bc3770129041e77">NRE::Math::Vector3D&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_math_1_1_vector4_d.php#ab3cf5aad969543b2881bdfc53715527c">NRE::Math::Vector4D&lt; T &gt;</a>
</li>
<li>ortho()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a60aa5a22281a42e16244875e6fca437e">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
<li>ortho2D()
: <a class="el" href="class_n_r_e_1_1_math_1_1_matrix4x4.php#a3713210c7ba1298fefc476385c84137b">NRE::Math::Matrix4x4&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
